<?php

use yii\db\Migration;

/**
 * Handles the creation of table `TimeZone`.
 */
class m180724_095137_create_TimeZone_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $tableOptions = null;

        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%TimeZone}}',
            [
                'TimeZoneId'=>"ENUM(
                                'Africa/Abidjan','Africa/Accra','Africa/Addis_Ababa','Africa/Algiers','Africa/Asmara','Africa/Bamako',
                                'Africa/Bangui','Africa/Banjul','Africa/Bissau','Africa/Blantyre','Africa/Brazzaville','Africa/Bujumbura',
                                'Africa/Cairo','Africa/Casablanca','Africa/Ceuta','Africa/Conakry','Africa/Dakar','Africa/Dar_es_Salaam',
                                'Africa/Djibouti','Africa/Douala','Africa/El_Aaiun','Africa/Freetown','Africa/Gaborone','Africa/Harare',
                                'Africa/Johannesburg','Africa/Juba','Africa/Kampala','Africa/Khartoum','Africa/Kigali','Africa/Kinshasa',
                                'Africa/Lagos','Africa/Libreville','Africa/Lome','Africa/Luanda','Africa/Lubumbashi','Africa/Lusaka',
                                'Africa/Malabo','Africa/Maputo','Africa/Maseru','Africa/Mbabane','Africa/Mogadishu','Africa/Monrovia',
                                'Africa/Nairobi','Africa/Ndjamena','Africa/Niamey','Africa/Nouakchott','Africa/Ouagadougou','Africa/Porto-Novo',
                                'Africa/Sao_Tome','Africa/Tripoli','Africa/Tunis','Africa/Windhoek','America/Adak','America/Anchorage',
                                'America/Anguilla','America/Antigua','America/Araguaina','America/Argentina/Buenos_Aires',
                                'America/Argentina/Catamarca','America/Argentina/Cordoba','America/Argentina/Jujuy',
                                'America/Argentina/La_Rioja','America/Argentina/Mendoza','America/Argentina/Rio_Gallegos',
                                'America/Argentina/Salta','America/Argentina/San_Juan','America/Argentina/San_Luis',
                                'America/Argentina/Tucuman','America/Argentina/Ushuaia','America/Aruba','America/Asuncion',
                                'America/Atikokan','America/Bahia','America/Bahia_Banderas','America/Barbados','America/Belem',
                                'America/Belize','America/Blanc-Sablon','America/Boa_Vista','America/Bogota','America/Boise',
                                'America/Cambridge_Bay','America/Campo_Grande','America/Cancun','America/Caracas',
                                'America/Cayenne','America/Cayman','America/Chicago','America/Chihuahua','America/Costa_Rica',
                                'America/Creston','America/Cuiaba','America/Curacao','America/Danmarkshavn','America/Dawson',
                                'America/Dawson_Creek','America/Denver','America/Detroit','America/Dominica','America/Edmonton',
                                'America/Eirunepe','America/El_Salvador','America/Fortaleza','America/Fort_Nelson','America/Glace_Bay',
                                'America/Godthab','America/Goose_Bay','America/Grand_Turk','America/Grenada','America/Guadeloupe',
                                'America/Guatemala','America/Guayaquil','America/Guyana','America/Halifax','America/Havana',
                                'America/Hermosillo','America/Indiana/Indianapolis','America/Indiana/Knox','America/Indiana/Marengo',
                                'America/Indiana/Petersburg','America/Indiana/Tell_City','America/Indiana/Vevay','America/Indiana/Vincennes',
                                'America/Indiana/Winamac','America/Inuvik','America/Iqaluit','America/Jamaica','America/Juneau',
                                'America/Kentucky/Louisville','America/Kentucky/Monticello','America/Kralendijk','America/La_Paz',
                                'America/Lima','America/Los_Angeles','America/Lower_Princes','America/Maceio','America/Managua',
                                'America/Manaus','America/Marigot','America/Martinique','America/Matamoros','America/Mazatlan',
                                'America/Menominee','America/Merida','America/Metlakatla','America/Mexico_City','America/Miquelon',
                                'America/Moncton','America/Monterrey','America/Montevideo','America/Montserrat','America/Nassau',
                                'America/New_York','America/Nipigon','America/Nome','America/Noronha','America/North_Dakota/Beulah',
                                'America/North_Dakota/Center','America/North_Dakota/New_Salem','America/Ojinaga','America/Panama',
                                'America/Pangnirtung','America/Paramaribo','America/Phoenix','America/Port-au-Prince','America/Porto_Velho',
                                'America/Port_of_Spain','America/Puerto_Rico','America/Punta_Arenas','America/Rainy_River',
                                'America/Rankin_Inlet','America/Recife','America/Regina','America/Resolute','America/Rio_Branco',
                                'America/Santarem','America/Santiago','America/Santo_Domingo','America/Sao_Paulo','America/Scoresbysund',
                                'America/Sitka','America/St_Barthelemy','America/St_Johns','America/St_Kitts','America/St_Lucia',
                                'America/St_Thomas','America/St_Vincent','America/Swift_Current','America/Tegucigalpa','America/Thule',
                                'America/Thunder_Bay','America/Tijuana','America/Toronto','America/Tortola','America/Vancouver',
                                'America/Whitehorse','America/Winnipeg','America/Yakutat','America/Yellowknife','Antarctica/Casey',
                                'Antarctica/Davis','Antarctica/DumontDUrville','Antarctica/Macquarie','Antarctica/Mawson',
                                'Antarctica/McMurdo','Antarctica/Palmer','Antarctica/Rothera','Antarctica/Syowa','Antarctica/Troll',
                                'Antarctica/Vostok','Arctic/Longyearbyen','Asia/Aden','Asia/Almaty','Asia/Amman','Asia/Anadyr',
                                'Asia/Aqtau','Asia/Aqtobe','Asia/Ashgabat','Asia/Atyrau','Asia/Baghdad','Asia/Bahrain','Asia/Baku',
                                'Asia/Bangkok','Asia/Barnaul','Asia/Beirut','Asia/Bishkek','Asia/Brunei','Asia/Chita','Asia/Choibalsan',
                                'Asia/Colombo','Asia/Damascus','Asia/Dhaka','Asia/Dili','Asia/Dubai','Asia/Dushanbe','Asia/Famagusta',
                                'Asia/Gaza','Asia/Hebron','Asia/Hong_Kong','Asia/Hovd','Asia/Ho_Chi_Minh','Asia/Irkutsk','Asia/Jakarta',
                                'Asia/Jayapura','Asia/Jerusalem','Asia/Kabul','Asia/Kamchatka','Asia/Karachi','Asia/Kathmandu','Asia/Khandyga',
                                'Asia/Kolkata','Asia/Krasnoyarsk','Asia/Kuala_Lumpur','Asia/Kuching','Asia/Kuwait','Asia/Macau',
                                'Asia/Magadan','Asia/Makassar','Asia/Manila','Asia/Muscat','Asia/Nicosia','Asia/Novokuznetsk','Asia/Novosibirsk',
                                'Asia/Omsk','Asia/Oral','Asia/Phnom_Penh','Asia/Pontianak','Asia/Pyongyang','Asia/Qatar','Asia/Qyzylorda',
                                'Asia/Riyadh','Asia/Sakhalin','Asia/Samarkand','Asia/Seoul','Asia/Shanghai','Asia/Singapore',
                                'Asia/Srednekolymsk','Asia/Taipei','Asia/Tashkent','Asia/Tbilisi','Asia/Tehran','Asia/Thimphu',
                                'Asia/Tokyo','Asia/Tomsk','Asia/Ulaanbaatar','Asia/Urumqi','Asia/Ust-Nera','Asia/Vientiane',
                                'Asia/Vladivostok','Asia/Yakutsk','Asia/Yangon','Asia/Yekaterinburg','Asia/Yerevan','Atlantic/Azores',
                                'Atlantic/Bermuda','Atlantic/Canary','Atlantic/Cape_Verde','Atlantic/Faroe','Atlantic/Madeira',
                                'Atlantic/Reykjavik','Atlantic/South_Georgia','Atlantic/Stanley','Atlantic/St_Helena',
                                'Australia/Adelaide','Australia/Brisbane','Australia/Broken_Hill','Australia/Currie','Australia/Darwin',
                                'Australia/Eucla','Australia/Hobart','Australia/Lindeman','Australia/Lord_Howe','Australia/Melbourne',
                                'Australia/Perth','Australia/Sydney','Europe/Amsterdam','Europe/Andorra','Europe/Astrakhan',
                                'Europe/Athens','Europe/Belgrade','Europe/Berlin','Europe/Bratislava','Europe/Brussels','Europe/Bucharest',
                                'Europe/Budapest','Europe/Busingen','Europe/Chisinau','Europe/Copenhagen','Europe/Dublin',
                                'Europe/Gibraltar','Europe/Guernsey','Europe/Helsinki','Europe/Isle_of_Man','Europe/Istanbul',
                                'Europe/Jersey','Europe/Kaliningrad','Europe/Kiev','Europe/Kirov','Europe/Lisbon','Europe/Ljubljana',
                                'Europe/London','Europe/Luxembourg','Europe/Madrid','Europe/Malta','Europe/Mariehamn','Europe/Minsk',
                                'Europe/Monaco','Europe/Moscow','Europe/Oslo','Europe/Paris','Europe/Podgorica','Europe/Prague',
                                'Europe/Riga','Europe/Rome','Europe/Samara','Europe/San_Marino','Europe/Sarajevo','Europe/Saratov',
                                'Europe/Simferopol','Europe/Skopje','Europe/Sofia','Europe/Stockholm','Europe/Tallinn','Europe/Tirane',
                                'Europe/Ulyanovsk','Europe/Uzhgorod','Europe/Vaduz','Europe/Vatican','Europe/Vienna','Europe/Vilnius',
                                'Europe/Volgograd','Europe/Warsaw','Europe/Zagreb','Europe/Zaporozhye','Europe/Zurich','Indian/Antananarivo',
                                'Indian/Chagos','Indian/Christmas','Indian/Cocos','Indian/Comoro','Indian/Kerguelen','Indian/Mahe',
                                'Indian/Maldives','Indian/Mauritius','Indian/Mayotte','Indian/Reunion','Pacific/Apia','Pacific/Auckland',
                                'Pacific/Bougainville','Pacific/Chatham','Pacific/Chuuk','Pacific/Easter','Pacific/Efate','Pacific/Enderbury',
                                'Pacific/Fakaofo','Pacific/Fiji','Pacific/Funafuti','Pacific/Galapagos','Pacific/Gambier',
                                'Pacific/Guadalcanal','Pacific/Guam','Pacific/Honolulu','Pacific/Kiritimati','Pacific/Kosrae',
                                'Pacific/Kwajalein','Pacific/Majuro','Pacific/Marquesas','Pacific/Midway','Pacific/Nauru',
                                'Pacific/Niue','Pacific/Norfolk','Pacific/Noumea','Pacific/Pago_Pago','Pacific/Palau','Pacific/Pitcairn',
                                'Pacific/Pohnpei','Pacific/Port_Moresby','Pacific/Rarotonga','Pacific/Saipan','Pacific/Tahiti',
                                'Pacific/Tarawa','Pacific/Tongatapu','Pacific/Wake','Pacific/Wallis' )  NOT NULL DEFAULT 'Europe/Moscow'",

                'CountryCode'=>"ENUM(
                                'AB','AD','AE','AF','AG','AI','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AW','AX','AZ',
                                'BA','BB','BD','BE','BF','BG','BH','BI','BJ','BL','BM','BN','BO','BQ','BR','BS','BT','BV',
                                'BW','BY','BZ','CA','CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','CR','CS','CU',
                                'CV','CW','CX','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG','EH','ER','ES','ET',
                                'FI','FJ','FK','FM','FO','FR','GA','GB','GD','GE','GF','GG','GH','GI','GL','GM','GN','GP',
                                'GQ','GR','GS','GT','GU','GW','GY','HK','HM','HN','HR','HT','HU','ID','IE','IL','IM','IN',
                                'IO','IQ','IR','IS','IT','JE','JM','JO','JP','KE','KG','KH','KI','KM','KN','KP','KR','KW',
                                'KY','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY','MA','MC','MD','ME','MF',
                                'MG','MH','MK','ML','MM','MN','MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ',
                                'NA','NC','NE','NF','NG','NI','NL','NO','NP','NR','NU','NZ','OM','OS','PA','PE','PF','PG',
                                'PH','PK','PL','PM','PN','PR','PS','PT','PW','PY','QA','RE','RO','RS','RU','RW','SA','SB',
                                'SC','SD','SE','SG','SH','SI','SJ','SK','SL','SM','SN','SO','SR','SS','ST','SV','SX','SY',
                                'SZ','TC','TD','TF','TG','TH','TJ','TK','TL','TM','TN','TO','TR','TT','TV','TW','TZ','UA',
                                'UG','UM','US','UY','UZ','VA','VC','VE','VG','VI','VN','VU','WF','WS','XK','YE','YT','ZA',
                                'ZM','ZW' ) NOT NULL DEFAULT 'RU'",

                'Code'=>"varchar(50) GENERATED ALWAYS AS (LOWER(REPLACE(`TimeZoneId`,'/','_'))) VIRTUAL",
                'Sort'=>'SMALLINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT',

                'GMT'=>$this->decimal(4,2)->notNull()->defaultValue('0.0'),
                'DST'=>$this->decimal(4,2)->notNull()->defaultValue('0.0'),
                'rawOffset'=>$this->decimal(4,2)->notNull()->defaultValue('0.0'),

                'GMTMonth'=>"ENUM('January','February','March','April','May','June','July','August','September','October','November','December') NOT NULL DEFAULT 'October'",
                'GMTWeek'=>"ENUM('FirstWeek','SecondWeek','ThirdWeek','FourthWeek','LastWeek' ) NOT NULL DEFAULT 'LastWeek'",
                'GMTDayOfWeek'=>"ENUM('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday' ) NOT NULL DEFAULT 'Sunday'",
                'GMTHour'=>$this->time()->defaultValue('01:00:00'),

                'DSTMonth'=>"ENUM('January','February','March','April','May','June','July','August','September','October','November','December') NOT NULL DEFAULT 'March'",
                'DSTWeek'=>"ENUM('FirstWeek','SecondWeek','ThirdWeek','FourthWeek','LastWeek' ) NOT NULL DEFAULT 'LastWeek'",
                'DSTDayOfWeek'=>"ENUM('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday' ) NOT NULL DEFAULT 'Sunday'",
                'DSTHour'=>$this->time()->defaultValue('01:00:00'),

                'CreatedDate' => 'TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
                'UpdatedDate' => 'TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',


            ],
            $tableOptions
        );

        $this->addPrimaryKey('PrimaryKey','{{%TimeZone}}','TimeZoneId');
        $this->createIndex('idx-CountryCode','{{%TimeZone}}','CountryCode');

        $this->execute("ALTER TABLE `TimeZone` DROP INDEX `Sort`, ADD INDEX `Sort` (`Sort`) USING BTREE;");

        $insert=[
            ['CI', 'Africa/Abidjan', '0.00', '0.00', '0.00'],
            ['GH', 'Africa/Accra', '0.00', '0.00', '0.00'],
            ['ET', 'Africa/Addis_Ababa', '3.00', '3.00', '3.00'],
            ['DZ', 'Africa/Algiers', '1.00', '1.00', '1.00'],
            ['ER', 'Africa/Asmara', '3.00', '3.00', '3.00'],
            ['ML', 'Africa/Bamako', '0.00', '0.00', '0.00'],
            ['CF', 'Africa/Bangui', '1.00', '1.00', '1.00'],
            ['GM', 'Africa/Banjul', '0.00', '0.00', '0.00'],
            ['GW', 'Africa/Bissau', '0.00', '0.00', '0.00'],
            ['MW', 'Africa/Blantyre', '2.00', '2.00', '2.00'],
            ['CG', 'Africa/Brazzaville', '1.00', '1.00', '1.00'],
            ['BI', 'Africa/Bujumbura', '2.00', '2.00', '2.00'],
            ['EG', 'Africa/Cairo', '2.00', '2.00', '2.00'],
            ['MA', 'Africa/Casablanca', '0.00', '1.00', '0.00'],
            ['ES', 'Africa/Ceuta', '1.00', '2.00', '1.00'],
            ['GN', 'Africa/Conakry', '0.00', '0.00', '0.00'],
            ['SN', 'Africa/Dakar', '0.00', '0.00', '0.00'],
            ['TZ', 'Africa/Dar_es_Salaam', '3.00', '3.00', '3.00'],
            ['DJ', 'Africa/Djibouti', '3.00', '3.00', '3.00'],
            ['CM', 'Africa/Douala', '1.00', '1.00', '1.00'],
            ['EH', 'Africa/El_Aaiun', '0.00', '1.00', '0.00'],
            ['SL', 'Africa/Freetown', '0.00', '0.00', '0.00'],
            ['BW', 'Africa/Gaborone', '2.00', '2.00', '2.00'],
            ['ZW', 'Africa/Harare', '2.00', '2.00', '2.00'],
            ['ZA', 'Africa/Johannesburg', '2.00', '2.00', '2.00'],
            ['SS', 'Africa/Juba', '3.00', '3.00', '3.00'],
            ['UG', 'Africa/Kampala', '3.00', '3.00', '3.00'],
            ['SD', 'Africa/Khartoum', '2.00', '2.00', '2.00'],
            ['RW', 'Africa/Kigali', '2.00', '2.00', '2.00'],
            ['CD', 'Africa/Kinshasa', '1.00', '1.00', '1.00'],
            ['NG', 'Africa/Lagos', '1.00', '1.00', '1.00'],
            ['GA', 'Africa/Libreville', '1.00', '1.00', '1.00'],
            ['TG', 'Africa/Lome', '0.00', '0.00', '0.00'],
            ['AO', 'Africa/Luanda', '1.00', '1.00', '1.00'],
            ['CD', 'Africa/Lubumbashi', '2.00', '2.00', '2.00'],
            ['ZM', 'Africa/Lusaka', '2.00', '2.00', '2.00'],
            ['GQ', 'Africa/Malabo', '1.00', '1.00', '1.00'],
            ['MZ', 'Africa/Maputo', '2.00', '2.00', '2.00'],
            ['LS', 'Africa/Maseru', '2.00', '2.00', '2.00'],
            ['SZ', 'Africa/Mbabane', '2.00', '2.00', '2.00'],
            ['SO', 'Africa/Mogadishu', '3.00', '3.00', '3.00'],
            ['LR', 'Africa/Monrovia', '0.00', '0.00', '0.00'],
            ['KE', 'Africa/Nairobi', '3.00', '3.00', '3.00'],
            ['TD', 'Africa/Ndjamena', '1.00', '1.00', '1.00'],
            ['NE', 'Africa/Niamey', '1.00', '1.00', '1.00'],
            ['MR', 'Africa/Nouakchott', '0.00', '0.00', '0.00'],
            ['BF', 'Africa/Ouagadougou', '0.00', '0.00', '0.00'],
            ['BJ', 'Africa/Porto-Novo', '1.00', '1.00', '1.00'],
            ['ST', 'Africa/Sao_Tome', '0.00', '1.00', '1.00'],
            ['LY', 'Africa/Tripoli', '2.00', '2.00', '2.00'],
            ['TN', 'Africa/Tunis', '1.00', '1.00', '1.00'],
            ['NA', 'Africa/Windhoek', '2.00', '2.00', '2.00'],
            ['US', 'America/Adak', '-10.00', '-9.00', '-10.00'],
            ['US', 'America/Anchorage', '-9.00', '-8.00', '-9.00'],
            ['AI', 'America/Anguilla', '-4.00', '-4.00', '-4.00'],
            ['AG', 'America/Antigua', '-4.00', '-4.00', '-4.00'],
            ['BR', 'America/Araguaina', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/Buenos_Aires', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/Catamarca', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/Cordoba', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/Jujuy', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/La_Rioja', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/Mendoza', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/Rio_Gallegos', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/Salta', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/San_Juan', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/San_Luis', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/Tucuman', '-3.00', '-3.00', '-3.00'],
            ['AR', 'America/Argentina/Ushuaia', '-3.00', '-3.00', '-3.00'],
            ['AW', 'America/Aruba', '-4.00', '-4.00', '-4.00'],
            ['PY', 'America/Asuncion', '-3.00', '-4.00', '-4.00'],
            ['CA', 'America/Atikokan', '-5.00', '-5.00', '-5.00'],
            ['BR', 'America/Bahia', '-3.00', '-3.00', '-3.00'],
            ['MX', 'America/Bahia_Banderas', '-6.00', '-5.00', '-6.00'],
            ['BB', 'America/Barbados', '-4.00', '-4.00', '-4.00'],
            ['BR', 'America/Belem', '-3.00', '-3.00', '-3.00'],
            ['BZ', 'America/Belize', '-6.00', '-6.00', '-6.00'],
            ['CA', 'America/Blanc-Sablon', '-4.00', '-4.00', '-4.00'],
            ['BR', 'America/Boa_Vista', '-4.00', '-4.00', '-4.00'],
            ['CO', 'America/Bogota', '-5.00', '-5.00', '-5.00'],
            ['US', 'America/Boise', '-7.00', '-6.00', '-7.00'],
            ['CA', 'America/Cambridge_Bay', '-7.00', '-6.00', '-7.00'],
            ['BR', 'America/Campo_Grande', '-3.00', '-4.00', '-4.00'],
            ['MX', 'America/Cancun', '-5.00', '-5.00', '-5.00'],
            ['VE', 'America/Caracas', '-4.00', '-4.00', '-4.00'],
            ['GF', 'America/Cayenne', '-3.00', '-3.00', '-3.00'],
            ['KY', 'America/Cayman', '-5.00', '-5.00', '-5.00'],
            ['US', 'America/Chicago', '-6.00', '-5.00', '-6.00'],
            ['MX', 'America/Chihuahua', '-7.00', '-6.00', '-7.00'],
            ['CR', 'America/Costa_Rica', '-6.00', '-6.00', '-6.00'],
            ['CA', 'America/Creston', '-7.00', '-7.00', '-7.00'],
            ['BR', 'America/Cuiaba', '-3.00', '-4.00', '-4.00'],
            ['CW', 'America/Curacao', '-4.00', '-4.00', '-4.00'],
            ['GL', 'America/Danmarkshavn', '0.00', '0.00', '0.00'],
            ['CA', 'America/Dawson', '-8.00', '-7.00', '-8.00'],
            ['CA', 'America/Dawson_Creek', '-7.00', '-7.00', '-7.00'],
            ['US', 'America/Denver', '-7.00', '-6.00', '-7.00'],
            ['US', 'America/Detroit', '-5.00', '-4.00', '-5.00'],
            ['DM', 'America/Dominica', '-4.00', '-4.00', '-4.00'],
            ['CA', 'America/Edmonton', '-7.00', '-6.00', '-7.00'],
            ['BR', 'America/Eirunepe', '-5.00', '-5.00', '-5.00'],
            ['SV', 'America/El_Salvador', '-6.00', '-6.00', '-6.00'],
            ['BR', 'America/Fortaleza', '-3.00', '-3.00', '-3.00'],
            ['CA', 'America/Fort_Nelson', '-7.00', '-7.00', '-7.00'],
            ['CA', 'America/Glace_Bay', '-4.00', '-3.00', '-4.00'],
            ['GL', 'America/Godthab', '-3.00', '-2.00', '-3.00'],
            ['CA', 'America/Goose_Bay', '-4.00', '-3.00', '-4.00'],
            ['TC', 'America/Grand_Turk', '-4.00', '-4.00', '-5.00'],
            ['GD', 'America/Grenada', '-4.00', '-4.00', '-4.00'],
            ['GP', 'America/Guadeloupe', '-4.00', '-4.00', '-4.00'],
            ['GT', 'America/Guatemala', '-6.00', '-6.00', '-6.00'],
            ['EC', 'America/Guayaquil', '-5.00', '-5.00', '-5.00'],
            ['GY', 'America/Guyana', '-4.00', '-4.00', '-4.00'],
            ['CA', 'America/Halifax', '-4.00', '-3.00', '-4.00'],
            ['CU', 'America/Havana', '-5.00', '-4.00', '-5.00'],
            ['MX', 'America/Hermosillo', '-7.00', '-7.00', '-7.00'],
            ['US', 'America/Indiana/Indianapolis', '-5.00', '-4.00', '-5.00'],
            ['US', 'America/Indiana/Knox', '-6.00', '-5.00', '-6.00'],
            ['US', 'America/Indiana/Marengo', '-5.00', '-4.00', '-5.00'],
            ['US', 'America/Indiana/Petersburg', '-5.00', '-4.00', '-5.00'],
            ['US', 'America/Indiana/Tell_City', '-6.00', '-5.00', '-6.00'],
            ['US', 'America/Indiana/Vevay', '-5.00', '-4.00', '-5.00'],
            ['US', 'America/Indiana/Vincennes', '-5.00', '-4.00', '-5.00'],
            ['US', 'America/Indiana/Winamac', '-5.00', '-4.00', '-5.00'],
            ['CA', 'America/Inuvik', '-7.00', '-6.00', '-7.00'],
            ['CA', 'America/Iqaluit', '-5.00', '-4.00', '-5.00'],
            ['JM', 'America/Jamaica', '-5.00', '-5.00', '-5.00'],
            ['US', 'America/Juneau', '-9.00', '-8.00', '-9.00'],
            ['US', 'America/Kentucky/Louisville', '-5.00', '-4.00', '-5.00'],
            ['US', 'America/Kentucky/Monticello', '-5.00', '-4.00', '-5.00'],
            ['BQ', 'America/Kralendijk', '-4.00', '-4.00', '-4.00'],
            ['BO', 'America/La_Paz', '-4.00', '-4.00', '-4.00'],
            ['PE', 'America/Lima', '-5.00', '-5.00', '-5.00'],
            ['US', 'America/Los_Angeles', '-8.00', '-7.00', '-8.00'],
            ['SX', 'America/Lower_Princes', '-4.00', '-4.00', '-4.00'],
            ['BR', 'America/Maceio', '-3.00', '-3.00', '-3.00'],
            ['NI', 'America/Managua', '-6.00', '-6.00', '-6.00'],
            ['BR', 'America/Manaus', '-4.00', '-4.00', '-4.00'],
            ['MF', 'America/Marigot', '-4.00', '-4.00', '-4.00'],
            ['MQ', 'America/Martinique', '-4.00', '-4.00', '-4.00'],
            ['MX', 'America/Matamoros', '-6.00', '-5.00', '-6.00'],
            ['MX', 'America/Mazatlan', '-7.00', '-6.00', '-7.00'],
            ['US', 'America/Menominee', '-6.00', '-5.00', '-6.00'],
            ['MX', 'America/Merida', '-6.00', '-5.00', '-6.00'],
            ['US', 'America/Metlakatla', '-9.00', '-8.00', '-9.00'],
            ['MX', 'America/Mexico_City', '-6.00', '-5.00', '-6.00'],
            ['PM', 'America/Miquelon', '-3.00', '-2.00', '-3.00'],
            ['CA', 'America/Moncton', '-4.00', '-3.00', '-4.00'],
            ['MX', 'America/Monterrey', '-6.00', '-5.00', '-6.00'],
            ['UY', 'America/Montevideo', '-3.00', '-3.00', '-3.00'],
            ['MS', 'America/Montserrat', '-4.00', '-4.00', '-4.00'],
            ['BS', 'America/Nassau', '-5.00', '-4.00', '-5.00'],
            ['US', 'America/New_York', '-5.00', '-4.00', '-5.00'],
            ['CA', 'America/Nipigon', '-5.00', '-4.00', '-5.00'],
            ['US', 'America/Nome', '-9.00', '-8.00', '-9.00'],
            ['BR', 'America/Noronha', '-2.00', '-2.00', '-2.00'],
            ['US', 'America/North_Dakota/Beulah', '-6.00', '-5.00', '-6.00'],
            ['US', 'America/North_Dakota/Center', '-6.00', '-5.00', '-6.00'],
            ['US', 'America/North_Dakota/New_Salem', '-6.00', '-5.00', '-6.00'],
            ['MX', 'America/Ojinaga', '-7.00', '-6.00', '-7.00'],
            ['PA', 'America/Panama', '-5.00', '-5.00', '-5.00'],
            ['CA', 'America/Pangnirtung', '-5.00', '-4.00', '-5.00'],
            ['SR', 'America/Paramaribo', '-3.00', '-3.00', '-3.00'],
            ['US', 'America/Phoenix', '-7.00', '-7.00', '-7.00'],
            ['HT', 'America/Port-au-Prince', '-5.00', '-4.00', '-5.00'],
            ['BR', 'America/Porto_Velho', '-4.00', '-4.00', '-4.00'],
            ['TT', 'America/Port_of_Spain', '-4.00', '-4.00', '-4.00'],
            ['PR', 'America/Puerto_Rico', '-4.00', '-4.00', '-4.00'],
            ['CL', 'America/Punta_Arenas', '-3.00', '-3.00', '-3.00'],
            ['CA', 'America/Rainy_River', '-6.00', '-5.00', '-6.00'],
            ['CA', 'America/Rankin_Inlet', '-6.00', '-5.00', '-6.00'],
            ['BR', 'America/Recife', '-3.00', '-3.00', '-3.00'],
            ['CA', 'America/Regina', '-6.00', '-6.00', '-6.00'],
            ['CA', 'America/Resolute', '-6.00', '-5.00', '-6.00'],
            ['BR', 'America/Rio_Branco', '-5.00', '-5.00', '-5.00'],
            ['BR', 'America/Santarem', '-3.00', '-3.00', '-3.00'],
            ['CL', 'America/Santiago', '-3.00', '-4.00', '-4.00'],
            ['DO', 'America/Santo_Domingo', '-4.00', '-4.00', '-4.00'],
            ['BR', 'America/Sao_Paulo', '-2.00', '-3.00', '-3.00'],
            ['GL', 'America/Scoresbysund', '-1.00', '0.00', '-1.00'],
            ['US', 'America/Sitka', '-9.00', '-8.00', '-9.00'],
            ['BL', 'America/St_Barthelemy', '-4.00', '-4.00', '-4.00'],
            ['CA', 'America/St_Johns', '-3.50', '-2.50', '-3.50'],
            ['KN', 'America/St_Kitts', '-4.00', '-4.00', '-4.00'],
            ['LC', 'America/St_Lucia', '-4.00', '-4.00', '-4.00'],
            ['VI', 'America/St_Thomas', '-4.00', '-4.00', '-4.00'],
            ['VC', 'America/St_Vincent', '-4.00', '-4.00', '-4.00'],
            ['CA', 'America/Swift_Current', '-6.00', '-6.00', '-6.00'],
            ['HN', 'America/Tegucigalpa', '-6.00', '-6.00', '-6.00'],
            ['GL', 'America/Thule', '-4.00', '-3.00', '-4.00'],
            ['CA', 'America/Thunder_Bay', '-5.00', '-4.00', '-5.00'],
            ['MX', 'America/Tijuana', '-8.00', '-7.00', '-8.00'],
            ['CA', 'America/Toronto', '-5.00', '-4.00', '-5.00'],
            ['VG', 'America/Tortola', '-4.00', '-4.00', '-4.00'],
            ['CA', 'America/Vancouver', '-8.00', '-7.00', '-8.00'],
            ['CA', 'America/Whitehorse', '-8.00', '-7.00', '-8.00'],
            ['CA', 'America/Winnipeg', '-6.00', '-5.00', '-6.00'],
            ['US', 'America/Yakutat', '-9.00', '-8.00', '-9.00'],
            ['CA', 'America/Yellowknife', '-7.00', '-6.00', '-7.00'],
            ['AQ', 'Antarctica/Casey', '11.00', '8.00', '8.00'],
            ['AQ', 'Antarctica/Davis', '7.00', '7.00', '7.00'],
            ['AQ', 'Antarctica/DumontDUrville', '10.00', '10.00', '10.00'],
            ['AU', 'Antarctica/Macquarie', '11.00', '11.00', '11.00'],
            ['AQ', 'Antarctica/Mawson', '5.00', '5.00', '5.00'],
            ['AQ', 'Antarctica/McMurdo', '13.00', '12.00', '12.00'],
            ['AQ', 'Antarctica/Palmer', '-3.00', '-3.00', '-3.00'],
            ['AQ', 'Antarctica/Rothera', '-3.00', '-3.00', '-3.00'],
            ['AQ', 'Antarctica/Syowa', '3.00', '3.00', '3.00'],
            ['AQ', 'Antarctica/Troll', '0.00', '2.00', '0.00'],
            ['AQ', 'Antarctica/Vostok', '6.00', '6.00', '6.00'],
            ['SJ', 'Arctic/Longyearbyen', '1.00', '2.00', '1.00'],
            ['YE', 'Asia/Aden', '3.00', '3.00', '3.00'],
            ['KZ', 'Asia/Almaty', '6.00', '6.00', '6.00'],
            ['JO', 'Asia/Amman', '2.00', '3.00', '2.00'],
            ['RU', 'Asia/Anadyr', '12.00', '12.00', '12.00'],
            ['KZ', 'Asia/Aqtau', '5.00', '5.00', '5.00'],
            ['KZ', 'Asia/Aqtobe', '5.00', '5.00', '5.00'],
            ['TM', 'Asia/Ashgabat', '5.00', '5.00', '5.00'],
            ['KZ', 'Asia/Atyrau', '5.00', '5.00', '5.00'],
            ['IQ', 'Asia/Baghdad', '3.00', '3.00', '3.00'],
            ['BH', 'Asia/Bahrain', '3.00', '3.00', '3.00'],
            ['AZ', 'Asia/Baku', '4.00', '4.00', '4.00'],
            ['TH', 'Asia/Bangkok', '7.00', '7.00', '7.00'],
            ['RU', 'Asia/Barnaul', '7.00', '7.00', '7.00'],
            ['LB', 'Asia/Beirut', '2.00', '3.00', '2.00'],
            ['KG', 'Asia/Bishkek', '6.00', '6.00', '6.00'],
            ['BN', 'Asia/Brunei', '8.00', '8.00', '8.00'],
            ['RU', 'Asia/Chita', '9.00', '9.00', '9.00'],
            ['MN', 'Asia/Choibalsan', '8.00', '8.00', '8.00'],
            ['LK', 'Asia/Colombo', '5.50', '5.50', '5.50'],
            ['SY', 'Asia/Damascus', '2.00', '3.00', '2.00'],
            ['BD', 'Asia/Dhaka', '6.00', '6.00', '6.00'],
            ['TL', 'Asia/Dili', '9.00', '9.00', '9.00'],
            ['AE', 'Asia/Dubai', '4.00', '4.00', '4.00'],
            ['TJ', 'Asia/Dushanbe', '5.00', '5.00', '5.00'],
            ['CY', 'Asia/Famagusta', '2.00', '3.00', '2.00'],
            ['PS', 'Asia/Gaza', '2.00', '3.00', '2.00'],
            ['PS', 'Asia/Hebron', '2.00', '3.00', '2.00'],
            ['HK', 'Asia/Hong_Kong', '8.00', '8.00', '8.00'],
            ['MN', 'Asia/Hovd', '7.00', '7.00', '7.00'],
            ['VN', 'Asia/Ho_Chi_Minh', '7.00', '7.00', '7.00'],
            ['RU', 'Asia/Irkutsk', '8.00', '8.00', '8.00'],
            ['ID', 'Asia/Jakarta', '7.00', '7.00', '7.00'],
            ['ID', 'Asia/Jayapura', '9.00', '9.00', '9.00'],
            ['IL', 'Asia/Jerusalem', '2.00', '3.00', '2.00'],
            ['AF', 'Asia/Kabul', '4.50', '4.50', '4.50'],
            ['RU', 'Asia/Kamchatka', '12.00', '12.00', '12.00'],
            ['PK', 'Asia/Karachi', '5.00', '5.00', '5.00'],
            ['NP', 'Asia/Kathmandu', '5.75', '5.75', '5.75'],
            ['RU', 'Asia/Khandyga', '9.00', '9.00', '9.00'],
            ['IN', 'Asia/Kolkata', '5.50', '5.50', '5.50'],
            ['RU', 'Asia/Krasnoyarsk', '7.00', '7.00', '7.00'],
            ['MY', 'Asia/Kuala_Lumpur', '8.00', '8.00', '8.00'],
            ['MY', 'Asia/Kuching', '8.00', '8.00', '8.00'],
            ['KW', 'Asia/Kuwait', '3.00', '3.00', '3.00'],
            ['MO', 'Asia/Macau', '8.00', '8.00', '8.00'],
            ['RU', 'Asia/Magadan', '11.00', '11.00', '11.00'],
            ['ID', 'Asia/Makassar', '8.00', '8.00', '8.00'],
            ['PH', 'Asia/Manila', '8.00', '8.00', '8.00'],
            ['OM', 'Asia/Muscat', '4.00', '4.00', '4.00'],
            ['CY', 'Asia/Nicosia', '2.00', '3.00', '2.00'],
            ['RU', 'Asia/Novokuznetsk', '7.00', '7.00', '7.00'],
            ['RU', 'Asia/Novosibirsk', '7.00', '7.00', '7.00'],
            ['RU', 'Asia/Omsk', '6.00', '6.00', '6.00'],
            ['KZ', 'Asia/Oral', '5.00', '5.00', '5.00'],
            ['KH', 'Asia/Phnom_Penh', '7.00', '7.00', '7.00'],
            ['ID', 'Asia/Pontianak', '7.00', '7.00', '7.00'],
            ['KP', 'Asia/Pyongyang', '8.50', '9.00', '9.00'],
            ['QA', 'Asia/Qatar', '3.00', '3.00', '3.00'],
            ['KZ', 'Asia/Qyzylorda', '6.00', '6.00', '6.00'],
            ['SA', 'Asia/Riyadh', '3.00', '3.00', '3.00'],
            ['RU', 'Asia/Sakhalin', '11.00', '11.00', '11.00'],
            ['UZ', 'Asia/Samarkand', '5.00', '5.00', '5.00'],
            ['KR', 'Asia/Seoul', '9.00', '9.00', '9.00'],
            ['CN', 'Asia/Shanghai', '8.00', '8.00', '8.00'],
            ['SG', 'Asia/Singapore', '8.00', '8.00', '8.00'],
            ['RU', 'Asia/Srednekolymsk', '11.00', '11.00', '11.00'],
            ['TW', 'Asia/Taipei', '8.00', '8.00', '8.00'],
            ['UZ', 'Asia/Tashkent', '5.00', '5.00', '5.00'],
            ['GE', 'Asia/Tbilisi', '4.00', '4.00', '4.00'],
            ['IR', 'Asia/Tehran', '3.50', '4.50', '3.50'],
            ['BT', 'Asia/Thimphu', '6.00', '6.00', '6.00'],
            ['JP', 'Asia/Tokyo', '9.00', '9.00', '9.00'],
            ['RU', 'Asia/Tomsk', '7.00', '7.00', '7.00'],
            ['MN', 'Asia/Ulaanbaatar', '8.00', '8.00', '8.00'],
            ['CN', 'Asia/Urumqi', '6.00', '6.00', '6.00'],
            ['RU', 'Asia/Ust-Nera', '10.00', '10.00', '10.00'],
            ['LA', 'Asia/Vientiane', '7.00', '7.00', '7.00'],
            ['RU', 'Asia/Vladivostok', '10.00', '10.00', '10.00'],
            ['RU', 'Asia/Yakutsk', '9.00', '9.00', '9.00'],
            ['MM', 'Asia/Yangon', '6.50', '6.50', '6.50'],
            ['RU', 'Asia/Yekaterinburg', '5.00', '5.00', '5.00'],
            ['AM', 'Asia/Yerevan', '4.00', '4.00', '4.00'],
            ['PT', 'Atlantic/Azores', '-1.00', '0.00', '-1.00'],
            ['BM', 'Atlantic/Bermuda', '-4.00', '-3.00', '-4.00'],
            ['ES', 'Atlantic/Canary', '0.00', '1.00', '0.00'],
            ['CV', 'Atlantic/Cape_Verde', '-1.00', '-1.00', '-1.00'],
            ['FO', 'Atlantic/Faroe', '0.00', '1.00', '0.00'],
            ['PT', 'Atlantic/Madeira', '0.00', '1.00', '0.00'],
            ['IS', 'Atlantic/Reykjavik', '0.00', '0.00', '0.00'],
            ['GS', 'Atlantic/South_Georgia', '-2.00', '-2.00', '-2.00'],
            ['FK', 'Atlantic/Stanley', '-3.00', '-3.00', '-3.00'],
            ['SH', 'Atlantic/St_Helena', '0.00', '0.00', '0.00'],
            ['AU', 'Australia/Adelaide', '10.50', '9.50', '9.50'],
            ['AU', 'Australia/Brisbane', '10.00', '10.00', '10.00'],
            ['AU', 'Australia/Broken_Hill', '10.50', '9.50', '9.50'],
            ['AU', 'Australia/Currie', '11.00', '10.00', '10.00'],
            ['AU', 'Australia/Darwin', '9.50', '9.50', '9.50'],
            ['AU', 'Australia/Eucla', '8.75', '8.75', '8.75'],
            ['AU', 'Australia/Hobart', '11.00', '10.00', '10.00'],
            ['AU', 'Australia/Lindeman', '10.00', '10.00', '10.00'],
            ['AU', 'Australia/Lord_Howe', '11.00', '10.50', '10.50'],
            ['AU', 'Australia/Melbourne', '11.00', '10.00', '10.00'],
            ['AU', 'Australia/Perth', '8.00', '8.00', '8.00'],
            ['AU', 'Australia/Sydney', '11.00', '10.00', '10.00'],
            ['NL', 'Europe/Amsterdam', '1.00', '2.00', '1.00'],
            ['AD', 'Europe/Andorra', '1.00', '2.00', '1.00'],
            ['RU', 'Europe/Astrakhan', '4.00', '4.00', '4.00'],
            ['GR', 'Europe/Athens', '2.00', '3.00', '2.00'],
            ['RS', 'Europe/Belgrade', '1.00', '2.00', '1.00'],
            ['DE', 'Europe/Berlin', '1.00', '2.00', '1.00'],
            ['SK', 'Europe/Bratislava', '1.00', '2.00', '1.00'],
            ['BE', 'Europe/Brussels', '1.00', '2.00', '1.00'],
            ['RO', 'Europe/Bucharest', '2.00', '3.00', '2.00'],
            ['HU', 'Europe/Budapest', '1.00', '2.00', '1.00'],
            ['DE', 'Europe/Busingen', '1.00', '2.00', '1.00'],
            ['MD', 'Europe/Chisinau', '2.00', '3.00', '2.00'],
            ['DK', 'Europe/Copenhagen', '1.00', '2.00', '1.00'],
            ['IE', 'Europe/Dublin', '0.00', '1.00', '1.00'],
            ['GI', 'Europe/Gibraltar', '1.00', '2.00', '1.00'],
            ['GG', 'Europe/Guernsey', '0.00', '1.00', '0.00'],
            ['FI', 'Europe/Helsinki', '2.00', '3.00', '2.00'],
            ['IM', 'Europe/Isle_of_Man', '0.00', '1.00', '0.00'],
            ['TR', 'Europe/Istanbul', '3.00', '3.00', '3.00'],
            ['JE', 'Europe/Jersey', '0.00', '1.00', '0.00'],
            ['RU', 'Europe/Kaliningrad', '2.00', '2.00', '2.00'],
            ['UA', 'Europe/Kiev', '2.00', '3.00', '2.00'],
            ['RU', 'Europe/Kirov', '3.00', '3.00', '3.00'],
            ['PT', 'Europe/Lisbon', '0.00', '1.00', '0.00'],
            ['SI', 'Europe/Ljubljana', '1.00', '2.00', '1.00'],
            ['GB', 'Europe/London', '0.00', '1.00', '0.00'],
            ['LU', 'Europe/Luxembourg', '1.00', '2.00', '1.00'],
            ['ES', 'Europe/Madrid', '1.00', '2.00', '1.00'],
            ['MT', 'Europe/Malta', '1.00', '2.00', '1.00'],
            ['AX', 'Europe/Mariehamn', '2.00', '3.00', '2.00'],
            ['BY', 'Europe/Minsk', '3.00', '3.00', '3.00'],
            ['MC', 'Europe/Monaco', '1.00', '2.00', '1.00'],
            ['RU', 'Europe/Moscow', '3.00', '3.00', '3.00'],
            ['NO', 'Europe/Oslo', '1.00', '2.00', '1.00'],
            ['FR', 'Europe/Paris', '1.00', '2.00', '1.00'],
            ['ME', 'Europe/Podgorica', '1.00', '2.00', '1.00'],
            ['CZ', 'Europe/Prague', '1.00', '2.00', '1.00'],
            ['LV', 'Europe/Riga', '2.00', '3.00', '2.00'],
            ['IT', 'Europe/Rome', '1.00', '2.00', '1.00'],
            ['RU', 'Europe/Samara', '4.00', '4.00', '4.00'],
            ['SM', 'Europe/San_Marino', '1.00', '2.00', '1.00'],
            ['BA', 'Europe/Sarajevo', '1.00', '2.00', '1.00'],
            ['RU', 'Europe/Saratov', '4.00', '4.00', '4.00'],
            ['RU', 'Europe/Simferopol', '3.00', '3.00', '3.00'],
            ['MK', 'Europe/Skopje', '1.00', '2.00', '1.00'],
            ['BG', 'Europe/Sofia', '2.00', '3.00', '2.00'],
            ['SE', 'Europe/Stockholm', '1.00', '2.00', '1.00'],
            ['EE', 'Europe/Tallinn', '2.00', '3.00', '2.00'],
            ['AL', 'Europe/Tirane', '1.00', '2.00', '1.00'],
            ['RU', 'Europe/Ulyanovsk', '4.00', '4.00', '4.00'],
            ['UA', 'Europe/Uzhgorod', '2.00', '3.00', '2.00'],
            ['LI', 'Europe/Vaduz', '1.00', '2.00', '1.00'],
            ['VA', 'Europe/Vatican', '1.00', '2.00', '1.00'],
            ['AT', 'Europe/Vienna', '1.00', '2.00', '1.00'],
            ['LT', 'Europe/Vilnius', '2.00', '3.00', '2.00'],
            ['RU', 'Europe/Volgograd', '3.00', '3.00', '3.00'],
            ['PL', 'Europe/Warsaw', '1.00', '2.00', '1.00'],
            ['HR', 'Europe/Zagreb', '1.00', '2.00', '1.00'],
            ['UA', 'Europe/Zaporozhye', '2.00', '3.00', '2.00'],
            ['CH', 'Europe/Zurich', '1.00', '2.00', '1.00'],
            ['MG', 'Indian/Antananarivo', '3.00', '3.00', '3.00'],
            ['IO', 'Indian/Chagos', '6.00', '6.00', '6.00'],
            ['CX', 'Indian/Christmas', '7.00', '7.00', '7.00'],
            ['CC', 'Indian/Cocos', '6.50', '6.50', '6.50'],
            ['KM', 'Indian/Comoro', '3.00', '3.00', '3.00'],
            ['TF', 'Indian/Kerguelen', '5.00', '5.00', '5.00'],
            ['SC', 'Indian/Mahe', '4.00', '4.00', '4.00'],
            ['MV', 'Indian/Maldives', '5.00', '5.00', '5.00'],
            ['MU', 'Indian/Mauritius', '4.00', '4.00', '4.00'],
            ['YT', 'Indian/Mayotte', '3.00', '3.00', '3.00'],
            ['RE', 'Indian/Reunion', '4.00', '4.00', '4.00'],
            ['WS', 'Pacific/Apia', '14.00', '13.00', '13.00'],
            ['NZ', 'Pacific/Auckland', '13.00', '12.00', '12.00'],
            ['PG', 'Pacific/Bougainville', '11.00', '11.00', '11.00'],
            ['NZ', 'Pacific/Chatham', '13.75', '12.75', '12.75'],
            ['FM', 'Pacific/Chuuk', '10.00', '10.00', '10.00'],
            ['CL', 'Pacific/Easter', '-5.00', '-6.00', '-6.00'],
            ['VU', 'Pacific/Efate', '11.00', '11.00', '11.00'],
            ['KI', 'Pacific/Enderbury', '13.00', '13.00', '13.00'],
            ['TK', 'Pacific/Fakaofo', '13.00', '13.00', '13.00'],
            ['FJ', 'Pacific/Fiji', '13.00', '12.00', '12.00'],
            ['TV', 'Pacific/Funafuti', '12.00', '12.00', '12.00'],
            ['EC', 'Pacific/Galapagos', '-6.00', '-6.00', '-6.00'],
            ['PF', 'Pacific/Gambier', '-9.00', '-9.00', '-9.00'],
            ['SB', 'Pacific/Guadalcanal', '11.00', '11.00', '11.00'],
            ['GU', 'Pacific/Guam', '10.00', '10.00', '10.00'],
            ['US', 'Pacific/Honolulu', '-10.00', '-10.00', '-10.00'],
            ['KI', 'Pacific/Kiritimati', '14.00', '14.00', '14.00'],
            ['FM', 'Pacific/Kosrae', '11.00', '11.00', '11.00'],
            ['MH', 'Pacific/Kwajalein', '12.00', '12.00', '12.00'],
            ['MH', 'Pacific/Majuro', '12.00', '12.00', '12.00'],
            ['PF', 'Pacific/Marquesas', '-9.50', '-9.50', '-9.50'],
            ['UM', 'Pacific/Midway', '-11.00', '-11.00', '-11.00'],
            ['NR', 'Pacific/Nauru', '12.00', '12.00', '12.00'],
            ['NU', 'Pacific/Niue', '-11.00', '-11.00', '-11.00'],
            ['NF', 'Pacific/Norfolk', '11.00', '11.00', '11.00'],
            ['NC', 'Pacific/Noumea', '11.00', '11.00', '11.00'],
            ['AS', 'Pacific/Pago_Pago', '-11.00', '-11.00', '-11.00'],
            ['PW', 'Pacific/Palau', '9.00', '9.00', '9.00'],
            ['PN', 'Pacific/Pitcairn', '-8.00', '-8.00', '-8.00'],
            ['FM', 'Pacific/Pohnpei', '11.00', '11.00', '11.00'],
            ['PG', 'Pacific/Port_Moresby', '10.00', '10.00', '10.00'],
            ['CK', 'Pacific/Rarotonga', '-10.00', '-10.00', '-10.00'],
            ['MP', 'Pacific/Saipan', '10.00', '10.00', '10.00'],
            ['PF', 'Pacific/Tahiti', '-10.00', '-10.00', '-10.00'],
            ['KI', 'Pacific/Tarawa', '12.00', '12.00', '12.00'],
            ['TO', 'Pacific/Tongatapu', '13.00', '13.00', '13.00'],
            ['UM', 'Pacific/Wake', '12.00', '12.00', '12.00'],
            ['WF', 'Pacific/Wallis', '12.00', '12.00', '12.00'],
        ];

        $this->batchInsert('{{%TimeZone}}',['CountryCode','TimeZoneId','GMT','DST','rawOffset'],$insert);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%TimeZone}}');
    }
}
