<?php

use yii\db\Migration;

/**
 * Handles the creation of table `Language`.
 */
class m180723_075913_create_Language_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $tableOptions = null;

        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable(
            '{{%Language}}',
            [
                'LanguageCode'=>"ENUM('aa','ab','ae','af','ak','am','an','ar','as','av','ay','az','ba','be','bg','bh',
                                        'bi','bm','bn','bo','br','bs','ca','ce','ch','co','cr','cs','cu','cv','cy','da',
                                        'de','dv','dz','ee','el','en','eo','es','et','eu','fa','ff','fi','fl','fj','fo','fr',
                                        'fy','ga','gd','gl','gn','gu','gv','ha','he','hi','ho','hr','ht','hu','hy','hz',
                                        'ia','id','ie','ig','ii','ik','io','is','it','iu','ja','jv','ka','kg','ki','kj',
                                        'kk','kl','km','kn','ko','kr','ks','ku','kv','kw','ky','la','lb','lg','li','ln',
                                        'lo','lt','lu','lv','mg','mh','mi','mk','ml','mn','mr','ms','mt','my','na','nb',
                                        'nd','ne','ng','nl','nn','no','nr','nv','ny','oc','oj','om','or','os','pa','pi',
                                        'pl','ps','pt','qu','rm','rn','ro','ru','rw','sa','sc','sd','se','sg','sh','si',
                                        'sk','sl','sm','sn','so','sq','sr','ss','st','su','sv','sw','ta','te','tg','th',
                                        'ti','tk','tl','tn','to','tr','ts','tt','tw','ty','ug','uk','ur','uz','ve','vi',
                                        'vo','wa','wo','xh','yi','yo','za','zh','zu')  NOT NULL ",

                'Code'=>"varchar(80) GENERATED ALWAYS AS (LOWER(REPLACE(`Name`,' ','_'))) VIRTUAL",
                'Status' => "ENUM( 'active','inactive')  NOT NULL DEFAULT 'inactive'",
                'Sort'=>'TINYINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT',
                'Name' => $this->string(80)->notNull(),
                'CreatedDate' => 'TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
                'UpdatedDate' => 'TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
            ],
            $tableOptions
        );

        $this->addPrimaryKey('PrimaryKey','{{%Language}}','LanguageCode');

        $this->execute("ALTER TABLE `Language` DROP INDEX `Sort`, ADD INDEX `Sort` (`Sort`) USING BTREE;");

        $insert=
            [
                ['aa', 'Afar'],
                ['ab', 'Abkhazian'],
                ['ae', 'Avestan'],
                ['af', 'Afrikaans'],
                ['ak', 'Akan'],
                ['am', 'Amharic'],
                ['an', 'Aragonese'],
                ['ar', 'Arabic'],
                ['as', 'Assamese'],
                ['av', 'Avaric'],
                ['ay', 'Aymara'],
                ['az', 'Azerbaijani'],
                ['ba', 'Bashkir'],
                ['be', 'Belarusian'],
                ['bg', 'Bulgarian'],
                ['bh', 'Bihari'],
                ['bi', 'Bislama'],
                ['bm', 'Bambara'],
                ['bn', 'Bengali'],
                ['bo', 'Tibetan'],
                ['br', 'Breton'],
                ['bs', 'Bosnian'],
                ['ca', 'Catalan'],
                ['ce', 'Chechen'],
                ['ch', 'Chamorro'],
                ['co', 'Corsican'],
                ['cr', 'Cree'],
                ['cs', 'Czech'],
                ['cu', 'Church Slavic'],
                ['cv', 'Chuvash'],
                ['cy', 'Welsh'],
                ['da', 'Danish'],
                ['de', 'German'],
                ['dv', 'Dhivehi'],
                ['dz', 'Dzongkha'],
                ['ee', 'Ewe'],
                ['el', 'Modern Greek (1453-)'],
                ['en', 'English'],
                ['eo', 'Esperanto'],
                ['es', 'Spanish'],
                ['et', 'Estonian'],
                ['eu', 'Basque'],
                ['fa', 'Persian'],
                ['ff', 'Fulah'],
                ['fi', 'Finnish'],
                ['fl','Pilipino'],
                ['fj', 'Fijian'],
                ['fo', 'Faroese'],
                ['fr', 'French'],
                ['fy', 'Western Frisian'],
                ['ga', 'Irish'],
                ['gd', 'Scottish Gaelic'],
                ['gl', 'Galician'],
                ['gn', 'Guarani'],
                ['gu', 'Gujarati'],
                ['gv', 'Manx'],
                ['ha', 'Hausa'],
                ['he', 'Hebrew'],
                ['hi', 'Hindi'],
                ['ho', 'Hiri Motu'],
                ['hr', 'Croatian'],
                ['ht', 'Haitian'],
                ['hu', 'Hungarian'],
                ['hy', 'Armenian'],
                ['hz', 'Herero'],
                ['ia', 'Interlingua (International Auxiliary Language Association)'],
                ['id', 'Indonesian'],
                ['ie', 'Interlingue'],
                ['ig', 'Igbo'],
                ['ii', 'Sichuan Yi'],
                ['ik', 'Inupiaq'],
                ['io', 'Ido'],
                ['is', 'Icelandic'],
                ['it', 'Italian'],
                ['iu', 'Inuktitut'],
                ['ja', 'Japanese'],
                ['jv', 'Javanese'],
                ['ka', 'Georgian'],
                ['kg', 'Kongo'],
                ['ki', 'Kikuyu'],
                ['kj', 'Kuanyama'],
                ['kk', 'Kazakh'],
                ['kl', 'Kalaallisut'],
                ['km', 'Central Khmer'],
                ['kn', 'Kannada'],
                ['ko', 'Korean'],
                ['kr', 'Kanuri'],
                ['ks', 'Kashmiri'],
                ['ku', 'Kurdish'],
                ['kv', 'Komi'],
                ['kw', 'Cornish'],
                ['ky', 'Kirghiz'],
                ['la', 'Latin'],
                ['lb', 'Luxembourgish'],
                ['lg', 'Ganda'],
                ['li', 'Limburgan'],
                ['ln', 'Lingala'],
                ['lo', 'Lao'],
                ['lt', 'Lithuanian'],
                ['lu', 'Luba-Katanga'],
                ['lv', 'Latvian'],
                ['mg', 'Malagasy'],
                ['mh', 'Marshallese'],
                ['mi', 'Maori'],
                ['mk', 'Macedonian'],
                ['ml', 'Malayalam'],
                ['mn', 'Mongolian'],
                ['mr', 'Marathi'],
                ['ms', 'Malay (macrolanguage)'],
                ['mt', 'Maltese'],
                ['my', 'Burmese'],
                ['na', 'Nauru'],
                ['nb', 'Norwegian Bokmål'],
                ['nd', 'North Ndebele'],
                ['ne', 'Nepali (macrolanguage)'],
                ['ng', 'Ndonga'],
                ['nl', 'Dutch'],
                ['nn', 'Norwegian Nynorsk'],
                ['no', 'Norwegian'],
                ['nr', 'South Ndebele'],
                ['nv', 'Navajo'],
                ['ny', 'Nyanja'],
                ['oc', 'Occitan (post 1500)'],
                ['oj', 'Ojibwa'],
                ['om', 'Oromo'],
                ['or', 'Oriya (macrolanguage)'],
                ['os', 'Ossetian'],
                ['pa', 'Panjabi'],
                ['pi', 'Pali'],
                ['pl', 'Polish'],
                ['ps', 'Pushto'],
                ['pt', 'Portuguese'],
                ['qu', 'Quechua'],
                ['rm', 'Romansh'],
                ['rn', 'Rundi'],
                ['ro', 'Romanian'],
                ['ru', 'Russian'],
                ['rw', 'Kinyarwanda'],
                ['sa', 'Sanskrit'],
                ['sc', 'Sardinian'],
                ['sd', 'Sindhi'],
                ['se', 'Northern Sami'],
                ['sg', 'Sango'],
                ['sh', 'Serbo-Croatian'],
                ['si', 'Sinhala'],
                ['sk', 'Slovak'],
                ['sl', 'Slovenian'],
                ['sm', 'Samoan'],
                ['sn', 'Shona'],
                ['so', 'Somali'],
                ['sq', 'Albanian'],
                ['sr', 'Serbian'],
                ['ss', 'Swati'],
                ['st', 'Southern Sotho'],
                ['su', 'Sundanese'],
                ['sv', 'Swedish'],
                ['sw', 'Swahili (macrolanguage)'],
                ['ta', 'Tamil'],
                ['te', 'Telugu'],
                ['tg', 'Tajik'],
                ['th', 'Thai'],
                ['ti', 'Tigrinya'],
                ['tk', 'Turkmen'],
                ['tl', 'Tagalog'],
                ['tn', 'Tswana'],
                ['to', 'Tonga (Tonga Islands)'],
                ['tr', 'Turkish'],
                ['ts', 'Tsonga'],
                ['tt', 'Tatar'],
                ['tw', 'Twi'],
                ['ty', 'Tahitian'],
                ['ug', 'Uighur'],
                ['uk', 'Ukrainian'],
                ['ur', 'Urdu'],
                ['uz', 'Uzbek'],
                ['ve', 'Venda'],
                ['vi', 'Vietnamese'],
                ['vo', 'Volapük'],
                ['wa', 'Walloon'],
                ['wo', 'Wolof'],
                ['xh', 'Xhosa'],
                ['yi', 'Yiddish'],
                ['yo', 'Yoruba'],
                ['za', 'Zhuang'],
                ['zh', 'Chinese'],
                ['zu', 'Zulu']
            ];

        $this->batchInsert('{{%Language}}',['LanguageCode','Name'],$insert);

        $this->update('{{%Language}}',['Status'=>'active'],['LanguageCode'=>'ru']);

        $this->createIndex('idx-Status-Sort','{{%Language}}',['Status','Sort']);



        $this->createTable('{{%LanguageTranslation}}', [
            'LanguageCode'=>"ENUM('aa','ab','ae','af','ak','am','an','ar','as','av','ay','az','ba','be','bg','bh',
                                        'bi','bm','bn','bo','br','bs','ca','ce','ch','co','cr','cs','cu','cv','cy','da',
                                        'de','dv','dz','ee','el','en','eo','es','et','eu','fa','ff','fi','fl','fj','fo','fr',
                                        'fy','ga','gd','gl','gn','gu','gv','ha','he','hi','ho','hr','ht','hu','hy','hz',
                                        'ia','id','ie','ig','ii','ik','io','is','it','iu','ja','jv','ka','kg','ki','kj',
                                        'kk','kl','km','kn','ko','kr','ks','ku','kv','kw','ky','la','lb','lg','li','ln',
                                        'lo','lt','lu','lv','mg','mh','mi','mk','ml','mn','mr','ms','mt','my','na','nb',
                                        'nd','ne','ng','nl','nn','no','nr','nv','ny','oc','oj','om','or','os','pa','pi',
                                        'pl','ps','pt','qu','rm','rn','ro','ru','rw','sa','sc','sd','se','sg','sh','si',
                                        'sk','sl','sm','sn','so','sq','sr','ss','st','su','sv','sw','ta','te','tg','th',
                                        'ti','tk','tl','tn','to','tr','ts','tt','tw','ty','ug','uk','ur','uz','ve','vi',
                                        'vo','wa','wo','xh','yi','yo','za','zh','zu')  NOT NULL ",

            'Language'=>$this->string(2)->notNull()->defaultValue('en'),
            'Name' => $this->string(120)->notNull(),
            'CreatedDate' => 'TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'UpdatedDate' => 'TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
            $tableOptions);

        $this->addPrimaryKey('PrimaryKey','{{%LanguageTranslation}}',['LanguageCode','Language']);


        $insert=
            [
                ['aa', 'Afar'],
                ['ab', 'Abkhazian'],
                ['ae', 'Avestan'],
                ['af', 'Afrikaans'],
                ['ak', 'Akan'],
                ['am', 'Amharic'],
                ['an', 'Aragonese'],
                ['ar', 'Arabic'],
                ['as', 'Assamese'],
                ['av', 'Avaric'],
                ['ay', 'Aymara'],
                ['az', 'Azerbaijani'],
                ['ba', 'Bashkir'],
                ['be', 'Belarusian'],
                ['bg', 'Bulgarian'],
                ['bh', 'Bihari '],
                ['bi', 'Bislama'],
                ['bm', 'Bambara'],
                ['bn', 'Bengali'],
                ['bo', 'Tibetan'],
                ['br', 'Breton'],
                ['bs', 'Bosnian'],
                ['ca', 'Catalan'],
                ['ce', 'Chechen'],
                ['ch', 'Chamorro'],
                ['co', 'Corsican'],
                ['cr', 'Cree'],
                ['cs', 'Czech'],
                ['cu', 'Church Slavic'],
                ['cv', 'Chuvash'],
                ['cy', 'Welsh'],
                ['da', 'Danish'],
                ['de', 'German'],
                ['dv', 'Dhivehi'],
                ['dz', 'Dzongkha'],
                ['ee', 'Ewe'],
                ['el', 'Greek'],
                ['en', 'English'],
                ['eo', 'Esperanto'],
                ['es', 'Spanish'],
                ['et', 'Estonian'],
                ['eu', 'Basque'],
                ['fa', 'Persian'],
                ['ff', 'Fulah'],
                ['fi', 'Finnish'],
                ['fl','Pilipino'],
                ['fj', 'Fijian'],
                ['fo', 'Faroese'],
                ['fr', 'French'],
                ['fy', 'Western Frisian'],
                ['ga', 'Irish'],
                ['gd', 'Scottish Gaelic'],
                ['gl', 'Galician'],
                ['gn', 'Guarani'],
                ['gu', 'Gujarati'],
                ['gv', 'Manx'],
                ['ha', 'Hausa'],
                ['he', 'Hebrew'],
                ['hi', 'Hindi'],
                ['ho', 'Hiri Motu'],
                ['hr', 'Croatian'],
                ['ht', 'Haitian'],
                ['hu', 'Hungarian'],
                ['hy', 'Armenian'],
                ['hz', 'Herero'],
                ['ia', 'Interlingua'],
                ['id', 'Indonesian'],
                ['ie', 'Interlingue'],
                ['ig', 'Igbo'],
                ['ii', 'Sichuan Yi'],
                ['ik', 'Inupiaq'],
                ['io', 'Ido'],
                ['is', 'Icelandic'],
                ['it', 'Italian'],
                ['iu', 'Inuktitut'],
                ['ja', 'Japanese'],
                ['jv', 'Javanese'],
                ['ka', 'Georgian'],
                ['kg', 'Kongo'],
                ['ki', 'Kikuyu'],
                ['kj', 'Kuanyama'],
                ['kk', 'Kazakh'],
                ['kl', 'Kalaallisut'],
                ['km', 'Central Khmer'],
                ['kn', 'Kannada'],
                ['ko', 'Korean'],
                ['kr', 'Kanuri'],
                ['ks', 'Kashmiri'],
                ['ku', 'Kurdish'],
                ['kv', 'Komi'],
                ['kw', 'Cornish'],
                ['ky', 'Kirghiz'],
                ['la', 'Latin'],
                ['lb', 'Luxembourgish'],
                ['lg', 'Ganda'],
                ['li', 'Limburgan'],
                ['ln', 'Lingala'],
                ['lo', 'Lao'],
                ['lt', 'Lithuanian'],
                ['lu', 'Luba-Katanga'],
                ['lv', 'Latvian'],
                ['mg', 'Malagasy'],
                ['mh', 'Marshallese'],
                ['mi', 'Maori'],
                ['mk', 'Macedonian'],
                ['ml', 'Malayalam'],
                ['mn', 'Mongolian'],
                ['mr', 'Marathi'],
                ['ms', 'Malay'],
                ['mt', 'Maltese'],
                ['my', 'Burmese'],
                ['na', 'Nauru'],
                ['nb', 'Norwegian Bokmål'],
                ['nd', 'North Ndebele'],
                ['ne', 'Nepali'],
                ['ng', 'Ndonga'],
                ['nl', 'Dutch'],
                ['nn', 'Norwegian Nynorsk'],
                ['no', 'Norwegian'],
                ['nr', 'South Ndebele'],
                ['nv', 'Navajo'],
                ['ny', 'Nyanja'],
                ['oc', 'Occitan'],
                ['oj', 'Ojibwa'],
                ['om', 'Oromo'],
                ['or', 'Oriya'],
                ['os', 'Ossetian'],
                ['pa', 'Panjabi'],
                ['pi', 'Pali'],
                ['pl', 'Polish'],
                ['ps', 'Pushto'],
                ['pt', 'Portuguese'],
                ['qu', 'Quechua'],
                ['rm', 'Romansh'],
                ['rn', 'Rundi'],
                ['ro', 'Romanian'],
                ['ru', 'Russian'],
                ['rw', 'Kinyarwanda'],
                ['sa', 'Sanskrit'],
                ['sc', 'Sardinian'],
                ['sd', 'Sindhi'],
                ['se', 'Northern Sami'],
                ['sg', 'Sango'],
                ['sh', 'Serbo-Croatian'],
                ['si', 'Sinhala'],
                ['sk', 'Slovak'],
                ['sl', 'Slovenian'],
                ['sm', 'Samoan'],
                ['sn', 'Shona'],
                ['so', 'Somali'],
                ['sq', 'Albanian'],
                ['sr', 'Serbian'],
                ['ss', 'Swati'],
                ['st', 'Southern Sotho'],
                ['su', 'Sundanese'],
                ['sv', 'Swedish'],
                ['sw', 'Swahili'],
                ['ta', 'Tamil'],
                ['te', 'Telugu'],
                ['tg', 'Tajik'],
                ['th', 'Thai'],
                ['ti', 'Tigrinya'],
                ['tk', 'Turkmen'],
                ['tl', 'Tagalog'],
                ['tn', 'Tswana'],
                ['to', 'Tonga'],
                ['tr', 'Turkish'],
                ['ts', 'Tsonga'],
                ['tt', 'Tatar'],
                ['tw', 'Twi'],
                ['ty', 'Tahitian'],
                ['ug', 'Uighur'],
                ['uk', 'Ukrainian'],
                ['ur', 'Urdu'],
                ['uz', 'Uzbek'],
                ['ve', 'Venda'],
                ['vi', 'Vietnamese'],
                ['vo', 'Volapük'],
                ['wa', 'Walloon'],
                ['wo', 'Wolof'],
                ['xh', 'Xhosa'],
                ['yi', 'Yiddish'],
                ['yo', 'Yoruba'],
                ['za', 'Zhuang'],
                ['zh', 'Chinese'],
                ['zu', 'Zulu']
            ];

        $this->batchInsert('{{%LanguageTranslation}}',['LanguageCode','Name'],$insert);

        $insert=[
            ['Абхазский', 'ab','ru'],
            ['Аварский', 'av','ru'],
            ['Авестийский', 'ae','ru'],
            ['Азербайджанский', 'az','ru'],
            ['Аймара', 'ay','ru'],
            ['Акан', 'ak','ru'],
            ['Албанский', 'sq','ru'],
            ['Амхарский', 'am','ru'],
            ['Английский', 'en','ru'],
            ['Арабский', 'ar','ru'],
            ['Армянский', 'hy','ru'],
            ['Ассамский', 'as','ru'],
            ['Афарский', 'aa','ru'],
            ['Африкаанс', 'af','ru'],
            ['Бамбара', 'bm','ru'],
            ['Баскский', 'eu','ru'],
            ['Башкирский', 'ba','ru'],
            ['Белорусский', 'be','ru'],
            ['Бенгальский', 'bn','ru'],
            ['Бирманский', 'my','ru'],
            ['Бислама', 'bi','ru'],
            ['Болгарский', 'bg','ru'],
            ['Боснийский', 'bs','ru'],
            ['Бретонский', 'br','ru'],
            ['Валлийский', 'cy','ru'],
            ['Венгерский', 'hu','ru'],
            ['Венда', 've','ru'],
            ['Волапюк', 'vo','ru'],
            ['Волоф', 'wo','ru'],
            ['Вьетнамский', 'vi','ru'],
            ['Галисийский', 'gl','ru'],
            ['Ганда', 'lg','ru'],
            ['Гереро', 'hz','ru'],
            ['Гренландский', 'kl','ru'],
            ['Греческий', 'el','ru'],
            ['Грузинский', 'ka','ru'],
            ['Гуарани', 'gn','ru'],
            ['Гуджарати', 'gu','ru'],
            ['Гэльский', 'gd','ru'],
            ['Датский', 'da','ru'],
            ['Дзонг-кэ', 'dz','ru'],
            ['Дивехи', 'dv','ru'],
            ['Зулу', 'zu','ru'],
            ['Иврит', 'he','ru'],
            ['Игбо', 'ig','ru'],
            ['Идиш', 'yi','ru'],
            ['Индонезийский', 'id','ru'],
            ['Интерлингва', 'ia','ru'],
            ['Интерлингве', 'ie','ru'],
            ['Инуктитут', 'iu','ru'],
            ['Инупиак', 'ik','ru'],
            ['Ирландский', 'ga','ru'],
            ['Исландский', 'is','ru'],
            ['Испанский', 'es','ru'],
            ['Итальянский', 'it','ru'],
            ['Йоруба', 'yo','ru'],
            ['Казахский', 'kk','ru'],
            ['Каннада', 'kn','ru'],
            ['Канури', 'kr','ru'],
            ['Каталанский', 'ca','ru'],
            ['Кашмири', 'ks','ru'],
            ['Кечуа', 'qu','ru'],
            ['Кикуйю', 'ki','ru'],
            ['Киньяма', 'kj','ru'],
            ['Киргизский', 'ky','ru'],
            ['Китайский', 'zh','ru'],
            ['Коми', 'kv','ru'],
            ['Конго', 'kg','ru'],
            ['Корейский', 'ko','ru'],
            ['Корнский', 'kw','ru'],
            ['Корсиканский', 'co','ru'],
            ['Коса', 'xh','ru'],
            ['Курдский', 'ku','ru'],
            ['Кхмерский', 'km','ru'],
            ['Лаосский', 'lo','ru'],
            ['Латинский', 'la','ru'],
            ['Латышский', 'lv','ru'],
            ['Лингала', 'ln','ru'],
            ['Литовский', 'lt','ru'],
            ['Луба-катанга', 'lu','ru'],
            ['Люксембургский', 'lb','ru'],
            ['Македонский', 'mk','ru'],
            ['Малагасийский', 'mg','ru'],
            ['Малайский', 'ms','ru'],
            ['Малаялам', 'ml','ru'],
            ['Мальтийский', 'mt','ru'],
            ['Маори', 'mi','ru'],
            ['Маратхи', 'mr','ru'],
            ['Маршалльский', 'mh','ru'],
            // ['Мерянский', 'me','ru'],
            ['Монгольский', 'mn','ru'],
            ['Мэнский', 'gv','ru'],
            ['Навахо', 'nv','ru'],
            ['Науру', 'na','ru'],
            ['Ндебеле северный', 'nd','ru'],
            ['Ндебеле южный', 'nr','ru'],
            ['Ндунга', 'ng','ru'],
            ['Немецкий', 'de','ru'],
            ['Непальский', 'ne','ru'],
            ['Нидерландский', 'nl','ru'],
            ['Норвежский', 'no','ru'],
            ['Ньянджа', 'ny','ru'],
            ['Новонорвежский', 'nn','ru'],
            ['Оджибве', 'oj','ru'],
            ['Окситанский', 'oc','ru'],
            ['Ория', 'or','ru'],
            ['Оромо', 'om','ru'],
            ['Осетинский', 'os','ru'],
            ['Пали', 'pi','ru'],
            ['Пенджабский', 'pa','ru'],
            ['Персидский', 'fa','ru'],
            ['Польский', 'pl','ru'],
            ['Португальский', 'pt','ru'],
            ['Пушту', 'ps','ru'],
            ['Ретороманский', 'rm','ru'],
            ['Руанда', 'rw','ru'],
            ['Румынский', 'ro','ru'],
            ['Рунди', 'rn','ru'],
            ['Русский', 'ru','ru'],
            ['Самоанский', 'sm','ru'],
            ['Санго', 'sg','ru'],
            ['Санскрит', 'sa','ru'],
            ['Сардинский', 'sc','ru'],
            ['Свази', 'ss','ru'],
            ['Сербский', 'sr','ru'],
            ['Сингальский', 'si','ru'],
            ['Синдхи', 'sd','ru'],
            ['Словацкий', 'sk','ru'],
            ['Словенский', 'sl','ru'],
            ['Сомали', 'so','ru'],
            ['Сото южный', 'st','ru'],
            ['Суахили', 'sw','ru'],
            ['Сунданский', 'su','ru'],
            ['Тагальский', 'tl','ru'],
            ['Таджикский', 'tg','ru'],
            ['Тайский', 'th','ru'],
            ['Таитянский', 'ty','ru'],
            ['Тамильский', 'ta','ru'],
            ['Татарский', 'tt','ru'],
            ['Тви', 'tw','ru'],
            ['Телугу', 'te','ru'],
            ['Тибетский', 'bo','ru'],
            ['Тигринья', 'ti','ru'],
            ['Тонганский', 'to','ru'],
            ['Тсвана', 'tn','ru'],
            ['Тсонга', 'ts','ru'],
            ['Турецкий', 'tr','ru'],
            ['Туркменский', 'tk','ru'],
            ['Узбекский', 'uz','ru'],
            ['Уйгурский', 'ug','ru'],
            ['Украинский', 'uk','ru'],
            ['Урду', 'ur','ru'],
            ['Фарерский', 'fo','ru'],
            ['Фиджи', 'fj','ru'],
            ['Филиппинский', 'fl','ru'],
            ['Финский', 'fi','ru'],
            ['Французский', 'fr','ru'],
            ['Фризский', 'fy','ru'],
            ['Фулах', 'ff','ru'],
            ['Хауса', 'ha','ru'],
            ['Хинди', 'hi','ru'],
            ['Хиримоту', 'ho','ru'],
            ['Хорватский', 'hr','ru'],
            ['Старославянский', 'cu','ru'],
            ['Чаморро', 'ch','ru'],
            ['Чеченский', 'ce','ru'],
            ['Чешский', 'cs','ru'],
            ['Чжуанский', 'za','ru'],
            ['Чувашский', 'cv','ru'],
            ['Шведский', 'sv','ru'],
            ['Шона', 'sn','ru'],
            ['Эве', 'ee','ru'],
            ['Эсперанто', 'eo','ru'],
            ['Эстонский', 'et','ru'],
            ['Яванский', 'jv','ru'],
            ['Японский', 'ja','ru']
        ];

        $this->batchInsert('{{%LanguageTranslation}}',['Name','LanguageCode','Language'],$insert);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%LanguageTranslation}}');
        $this->dropTable('{{%Language}}');
    }
}
