<?php

use yii\db\Migration;

/**
 * Handles the creation of table `Country`.
 */
class m180730_084046_create_Country_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $tableOptions = null;

        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%Country}}',
            [
                'CountryCode'=>"ENUM(
                                'AB','AD','AE','AF','AG','AI','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AW','AX','AZ',
                                'BA','BB','BD','BE','BF','BG','BH','BI','BJ','BL','BM','BN','BO','BQ','BR','BS','BT','BV',
                                'BW','BY','BZ','CA','CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','CR','CS','CU',
                                'CV','CW','CX','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG','EH','ER','ES','ET',
                                'FI','FJ','FK','FM','FO','FR','GA','GB','GD','GE','GF','GG','GH','GI','GL','GM','GN','GP',
                                'GQ','GR','GS','GT','GU','GW','GY','HK','HM','HN','HR','HT','HU','ID','IE','IL','IM','IN',
                                'IO','IQ','IR','IS','IT','JE','JM','JO','JP','KE','KG','KH','KI','KM','KN','KP','KR','KW',
                                'KY','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY','MA','MC','MD','ME','MF',
                                'MG','MH','MK','ML','MM','MN','MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ',
                                'NA','NC','NE','NF','NG','NI','NL','NO','NP','NR','NU','NZ','OM','OS','PA','PE','PF','PG',
                                'PH','PK','PL','PM','PN','PR','PS','PT','PW','PY','QA','RE','RO','RS','RU','RW','SA','SB',
                                'SC','SD','SE','SG','SH','SI','SJ','SK','SL','SM','SN','SO','SR','SS','ST','SV','SX','SY',
                                'SZ','TC','TD','TF','TG','TH','TJ','TK','TL','TM','TN','TO','TR','TT','TV','TW','TZ','UA',
                                'UG','UM','US','UY','UZ','VA','VC','VE','VG','VI','VN','VU','WF','WS','XK','YE','YT','ZA',
                                'ZM','ZW' ) NOT NULL DEFAULT 'RU'",

                'ParentCountryCode'=>"ENUM(
                                'AB','AD','AE','AF','AG','AI','AL','AM','AN','AO','AQ','AR','AS','AT','AU','AW','AX','AZ',
                                'BA','BB','BD','BE','BF','BG','BH','BI','BJ','BL','BM','BN','BO','BQ','BR','BS','BT','BV',
                                'BW','BY','BZ','CA','CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','CR','CS','CU',
                                'CV','CW','CX','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG','EH','ER','ES','ET',
                                'FI','FJ','FK','FM','FO','FR','GA','GB','GD','GE','GF','GG','GH','GI','GL','GM','GN','GP',
                                'GQ','GR','GS','GT','GU','GW','GY','HK','HM','HN','HR','HT','HU','ID','IE','IL','IM','IN',
                                'IO','IQ','IR','IS','IT','JE','JM','JO','JP','KE','KG','KH','KI','KM','KN','KP','KR','KW',
                                'KY','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY','MA','MC','MD','ME','MF',
                                'MG','MH','MK','ML','MM','MN','MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ',
                                'NA','NC','NE','NF','NG','NI','NL','NO','NP','NR','NU','NZ','OM','OS','PA','PE','PF','PG',
                                'PH','PK','PL','PM','PN','PR','PS','PT','PW','PY','QA','RE','RO','RS','RU','RW','SA','SB',
                                'SC','SD','SE','SG','SH','SI','SJ','SK','SL','SM','SN','SO','SR','SS','ST','SV','SX','SY',
                                'SZ','TC','TD','TF','TG','TH','TJ','TK','TL','TM','TN','TO','TR','TT','TV','TW','TZ','UA',
                                'UG','UM','US','UY','UZ','VA','VC','VE','VG','VI','VN','VU','WF','WS','XK','YE','YT','ZA',
                                'ZM','ZW' ) DEFAULT NULL",

                'Code'=>"varchar(80) GENERATED ALWAYS AS (LOWER(REPLACE(`Name`,' ','_'))) VIRTUAL",
                'Status' => "ENUM( 'active','inactive')  NOT NULL DEFAULT 'inactive'",
                'Sort'=>'TINYINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT',
                'Name' => $this->string(80)->notNull(),
                'ContinentCode'=>"ENUM('AF','AS','EU','NA','OC','SA','AN') NOT NULL DEFAULT 'EU'",

                'CreatedDate' => 'TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
                'UpdatedDate' => 'TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',

            ],
            $tableOptions
        );

        $this->addPrimaryKey('PrimaryKey','{{%Country}}','CountryCode');

        $this->execute("ALTER TABLE `Country` DROP INDEX `Sort`, ADD INDEX `Sort` (`Sort`) USING BTREE;");

        $insert=[
            ['AB', 'Abkhazia', 'EU'],
            ['AD', 'Andorra', 'EU'],
            ['AE', 'United Arab Emirates', 'AS'],
            ['AF', 'Afghanistan', 'AS'],
            ['AG', 'Antigua and Barbuda', 'NA'],
            ['AI', 'Anguilla', 'NA'],
            ['AL', 'Albania', 'EU'],
            ['AM', 'Armenia', 'AS'],
            ['AN', 'Netherlands Antilles', 'NA'],
            ['AO', 'Angola', 'AF'],
            ['AQ', 'Antarctica', 'AN'],
            ['AR', 'Argentina', 'SA'],
            ['AS', 'American Samoa', 'OC'],
            ['AT', 'Austria', 'EU'],
            ['AU', 'Australia', 'OC'],
            ['AW', 'Aruba', 'NA'],
            ['AX', 'Aland Islands', 'EU'],
            ['AZ', 'Azerbaijan', 'AS'],
            ['BA', 'Bosnia and Herzegovina', 'EU'],
            ['BB', 'Barbados', 'NA'],
            ['BD', 'Bangladesh', 'AS'],
            ['BE', 'Belgium', 'EU'],
            ['BF', 'Burkina Faso', 'AF'],
            ['BG', 'Bulgaria', 'EU'],
            ['BH', 'Bahrain', 'AS'],
            ['BI', 'Burundi', 'AF'],
            ['BJ', 'Benin', 'AF'],
            ['BL', 'Saint Barthelemy', 'NA'],
            ['BM', 'Bermuda', 'NA'],
            ['BN', 'Brunei', 'AS'],
            ['BO', 'Bolivia', 'SA'],
            ['BQ', 'Bonaire, Saint Eustatius and Saba ', 'NA'],
            ['BR', 'Brazil', 'SA'],
            ['BS', 'Bahamas', 'NA'],
            ['BT', 'Bhutan', 'AS'],
            ['BV', 'Bouvet Island', 'AN'],
            ['BW', 'Botswana', 'AF'],
            ['BY', 'Belarus', 'EU'],
            ['BZ', 'Belize', 'NA'],
            ['CA', 'Canada', 'NA'],
            ['CC', 'Cocos Islands', 'AS'],
            ['CD', 'Democratic Republic of the Congo', 'AF'],
            ['CF', 'Central African Republic', 'AF'],
            ['CG', 'Republic of the Congo', 'AF'],
            ['CH', 'Switzerland', 'EU'],
            ['CI', 'Ivory Coast', 'AF'],
            ['CK', 'Cook Islands', 'OC'],
            ['CL', 'Chile', 'SA'],
            ['CM', 'Cameroon', 'AF'],
            ['CN', 'China', 'AS'],
            ['CO', 'Colombia', 'SA'],
            ['CR', 'Costa Rica', 'NA'],
            ['CS', 'Serbia and Montenegro', 'EU'],
            ['CU', 'Cuba', 'NA'],
            ['CV', 'Cape Verde', 'AF'],
            ['CW', 'Curacao', 'NA'],
            ['CX', 'Christmas Island', 'OC'],
            ['CY', 'Cyprus', 'EU'],
            ['CZ', 'Czechia', 'EU'],
            ['DE', 'Germany', 'EU'],
            ['DJ', 'Djibouti', 'AF'],
            ['DK', 'Denmark', 'EU'],
            ['DM', 'Dominica', 'NA'],
            ['DO', 'Dominican Republic', 'NA'],
            ['DZ', 'Algeria', 'AF'],
            ['EC', 'Ecuador', 'SA'],
            ['EE', 'Estonia', 'EU'],
            ['EG', 'Egypt', 'AF'],
            ['EH', 'Western Sahara', 'AF'],
            ['ER', 'Eritrea', 'AF'],
            ['ES', 'Spain', 'EU'],
            ['ET', 'Ethiopia', 'AF'],
            ['FI', 'Finland', 'EU'],
            ['FJ', 'Fiji', 'OC'],
            ['FK', 'Falkland Islands', 'SA'],
            ['FM', 'Micronesia', 'OC'],
            ['FO', 'Faroe Islands', 'EU'],
            ['FR', 'France', 'EU'],
            ['GA', 'Gabon', 'AF'],
            ['GB', 'United Kingdom', 'EU'],
            ['GD', 'Grenada', 'NA'],
            ['GE', 'Georgia', 'AS'],
            ['GF', 'French Guiana', 'SA'],
            ['GG', 'Guernsey', 'EU'],
            ['GH', 'Ghana', 'AF'],
            ['GI', 'Gibraltar', 'EU'],
            ['GL', 'Greenland', 'NA'],
            ['GM', 'Gambia', 'AF'],
            ['GN', 'Guinea', 'AF'],
            ['GP', 'Guadeloupe', 'NA'],
            ['GQ', 'Equatorial Guinea', 'AF'],
            ['GR', 'Greece', 'EU'],
            ['GS', 'South Georgia and the South Sandwich Islands', 'AN'],
            ['GT', 'Guatemala', 'NA'],
            ['GU', 'Guam', 'OC'],
            ['GW', 'Guinea-Bissau', 'AF'],
            ['GY', 'Guyana', 'SA'],
            ['HK', 'Hong Kong', 'AS'],
            ['HM', 'Heard Island and McDonald Islands', 'AN'],
            ['HN', 'Honduras', 'NA'],
            ['HR', 'Croatia', 'EU'],
            ['HT', 'Haiti', 'NA'],
            ['HU', 'Hungary', 'EU'],
            ['ID', 'Indonesia', 'AS'],
            ['IE', 'Ireland', 'EU'],
            ['IL', 'Israel', 'AS'],
            ['IM', 'Isle of Man', 'EU'],
            ['IN', 'India', 'AS'],
            ['IO', 'British Indian Ocean Territory', 'AS'],
            ['IQ', 'Iraq', 'AS'],
            ['IR', 'Iran', 'AS'],
            ['IS', 'Iceland', 'EU'],
            ['IT', 'Italy', 'EU'],
            ['JE', 'Jersey', 'EU'],
            ['JM', 'Jamaica', 'NA'],
            ['JO', 'Jordan', 'AS'],
            ['JP', 'Japan', 'AS'],
            ['KE', 'Kenya', 'AF'],
            ['KG', 'Kyrgyzstan', 'AS'],
            ['KH', 'Cambodia', 'AS'],
            ['KI', 'Kiribati', 'OC'],
            ['KM', 'Comoros', 'AF'],
            ['KN', 'Saint Kitts and Nevis', 'NA'],
            ['KP', 'North Korea', 'AS'],
            ['KR', 'South Korea', 'AS'],
            ['KW', 'Kuwait', 'AS'],
            ['KY', 'Cayman Islands', 'NA'],
            ['KZ', 'Kazakhstan', 'AS'],
            ['LA', 'Laos', 'AS'],
            ['LB', 'Lebanon', 'AS'],
            ['LC', 'Saint Lucia', 'NA'],
            ['LI', 'Liechtenstein', 'EU'],
            ['LK', 'Sri Lanka', 'AS'],
            ['LR', 'Liberia', 'AF'],
            ['LS', 'Lesotho', 'AF'],
            ['LT', 'Lithuania', 'EU'],
            ['LU', 'Luxembourg', 'EU'],
            ['LV', 'Latvia', 'EU'],
            ['LY', 'Libya', 'AF'],
            ['MA', 'Morocco', 'AF'],
            ['MC', 'Monaco', 'EU'],
            ['MD', 'Moldova', 'EU'],
            ['ME', 'Montenegro', 'EU'],
            ['MF', 'Saint Martin', 'NA'],
            ['MG', 'Madagascar', 'AF'],
            ['MH', 'Marshall Islands', 'OC'],
            ['MK', 'Macedonia', 'EU'],
            ['ML', 'Mali', 'AF'],
            ['MM', 'Myanmar', 'AS'],
            ['MN', 'Mongolia', 'AS'],
            ['MO', 'Macao', 'AS'],
            ['MP', 'Northern Mariana Islands', 'OC'],
            ['MQ', 'Martinique', 'NA'],
            ['MR', 'Mauritania', 'AF'],
            ['MS', 'Montserrat', 'NA'],
            ['MT', 'Malta', 'EU'],
            ['MU', 'Mauritius', 'AF'],
            ['MV', 'Maldives', 'AS'],
            ['MW', 'Malawi', 'AF'],
            ['MX', 'Mexico', 'NA'],
            ['MY', 'Malaysia', 'AS'],
            ['MZ', 'Mozambique', 'AF'],
            ['NA', 'Namibia', 'AF'],
            ['NC', 'New Caledonia', 'OC'],
            ['NE', 'Niger', 'AF'],
            ['NF', 'Norfolk Island', 'OC'],
            ['NG', 'Nigeria', 'AF'],
            ['NI', 'Nicaragua', 'NA'],
            ['NL', 'Netherlands', 'EU'],
            ['NO', 'Norway', 'EU'],
            ['NP', 'Nepal', 'AS'],
            ['NR', 'Nauru', 'OC'],
            ['NU', 'Niue', 'OC'],
            ['NZ', 'New Zealand', 'OC'],
            ['OM', 'Oman', 'AS'],
            ['OS', 'South Ossetia', 'EU'],
            ['PA', 'Panama', 'NA'],
            ['PE', 'Peru', 'SA'],
            ['PF', 'French Polynesia', 'OC'],
            ['PG', 'Papua New Guinea', 'OC'],
            ['PH', 'Philippines', 'AS'],
            ['PK', 'Pakistan', 'AS'],
            ['PL', 'Poland', 'EU'],
            ['PM', 'Saint Pierre and Miquelon', 'NA'],
            ['PN', 'Pitcairn', 'OC'],
            ['PR', 'Puerto Rico', 'NA'],
            ['PS', 'Palestinian Territory', 'AS'],
            ['PT', 'Portugal', 'EU'],
            ['PW', 'Palau', 'OC'],
            ['PY', 'Paraguay', 'SA'],
            ['QA', 'Qatar', 'AS'],
            ['RE', 'Reunion', 'AF'],
            ['RO', 'Romania', 'EU'],
            ['RS', 'Serbia', 'EU'],
            ['RU', 'Russia', 'EU'],
            ['RW', 'Rwanda', 'AF'],
            ['SA', 'Saudi Arabia', 'AS'],
            ['SB', 'Solomon Islands', 'OC'],
            ['SC', 'Seychelles', 'AF'],
            ['SD', 'Sudan', 'AF'],
            ['SE', 'Sweden', 'EU'],
            ['SG', 'Singapore', 'AS'],
            ['SH', 'Saint Helena', 'AF'],
            ['SI', 'Slovenia', 'EU'],
            ['SJ', 'Svalbard and Jan Mayen', 'EU'],
            ['SK', 'Slovakia', 'EU'],
            ['SL', 'Sierra Leone', 'AF'],
            ['SM', 'San Marino', 'EU'],
            ['SN', 'Senegal', 'AF'],
            ['SO', 'Somalia', 'AF'],
            ['SR', 'Suriname', 'SA'],
            ['SS', 'South Sudan', 'AF'],
            ['ST', 'Sao Tome and Principe', 'AF'],
            ['SV', 'El Salvador', 'NA'],
            ['SX', 'Sint Maarten', 'NA'],
            ['SY', 'Syria', 'AS'],
            ['SZ', 'Swaziland', 'AF'],
            ['TC', 'Turks and Caicos Islands', 'NA'],
            ['TD', 'Chad', 'AF'],
            ['TF', 'French Southern Territories', 'AN'],
            ['TG', 'Togo', 'AF'],
            ['TH', 'Thailand', 'AS'],
            ['TJ', 'Tajikistan', 'AS'],
            ['TK', 'Tokelau', 'OC'],
            ['TL', 'Timor Leste', 'OC'],
            ['TM', 'Turkmenistan', 'AS'],
            ['TN', 'Tunisia', 'AF'],
            ['TO', 'Tonga', 'OC'],
            ['TR', 'Turkey', 'AS'],
            ['TT', 'Trinidad and Tobago', 'NA'],
            ['TV', 'Tuvalu', 'OC'],
            ['TW', 'Taiwan', 'AS'],
            ['TZ', 'Tanzania', 'AF'],
            ['UA', 'Ukraine', 'EU'],
            ['UG', 'Uganda', 'AF'],
            ['UM', 'United States Minor Outlying Islands', 'OC'],
            ['US', 'United States', 'NA'],
            ['UY', 'Uruguay', 'SA'],
            ['UZ', 'Uzbekistan', 'AS'],
            ['VA', 'Vatican', 'EU'],
            ['VC', 'Saint Vincent and the Grenadines', 'NA'],
            ['VE', 'Venezuela', 'SA'],
            ['VG', 'British Virgin Islands', 'NA'],
            ['VI', 'U.S. Virgin Islands', 'NA'],
            ['VN', 'Vietnam', 'AS'],
            ['VU', 'Vanuatu', 'OC'],
            ['WF', 'Wallis and Futuna', 'OC'],
            ['WS', 'Samoa', 'OC'],
            ['XK', 'Kosovo', 'EU'],
            ['YE', 'Yemen', 'AS'],
            ['YT', 'Mayotte', 'AF'],
            ['ZA', 'South Africa', 'AF'],
            ['ZM', 'Zambia', 'AF'],
            ['ZW', 'Zimbabwe', 'AF']

        ];

        $this->batchInsert('{{%Country}}',['CountryCode','Name','ContinentCode'],$insert);

        $this->update('{{%Country}}',['Status'=>'active'],['in','CountryCode',['BY','RU','KZ']]);

        $this->createIndex('idx-Status-Sort','{{%Country}}',['Status','Sort']);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%Country}}');
    }
}
