<?php

use yii\db\Migration;

/**
 * Handles the creation of table `Language`.
 */
class m180723_075913_create_Language_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $tableOptions = null;

        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable(
            '{{%Language}}',
            [
                'LanguageCode'=>"ENUM('aa','ab','ae','af','ak','am','an','ar','as','av','ay','az','ba','be','bg','bh',
                                        'bi','bm','bn','bo','br','bs','ca','ce','ch','co','cr','cs','cu','cv','cy','da',
                                        'de','dv','dz','ee','el','en','eo','es','et','eu','fa','ff','fi','fl','fj','fo','fr',
                                        'fy','ga','gd','gl','gn','gu','gv','ha','he','hi','ho','hr','ht','hu','hy','hz',
                                        'ia','id','ie','ig','ii','ik','io','is','it','iu','ja','jv','ka','kg','ki','kj',
                                        'kk','kl','km','kn','ko','kr','ks','ku','kv','kw','ky','la','lb','lg','li','ln',
                                        'lo','lt','lu','lv','mg','mh','mi','mk','ml','mn','mr','ms','mt','my','na','nb',
                                        'nd','ne','ng','nl','nn','no','nr','nv','ny','oc','oj','om','or','os','pa','pi',
                                        'pl','ps','pt','qu','rm','rn','ro','ru','rw','sa','sc','sd','se','sg','sh','si',
                                        'sk','sl','sm','sn','so','sq','sr','ss','st','su','sv','sw','ta','te','tg','th',
                                        'ti','tk','tl','tn','to','tr','ts','tt','tw','ty','ug','uk','ur','uz','ve','vi',
                                        'vo','wa','wo','xh','yi','yo','za','zh','zu')  NOT NULL ",

                'Code'=>"varchar(80) GENERATED ALWAYS AS (LOWER(REPLACE(`Name`,' ','_'))) VIRTUAL",
                'Status' => "ENUM( 'active','inactive')  NOT NULL DEFAULT 'inactive'",
                'Sort'=>'TINYINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT',
                'Name' => $this->string(80)->notNull(),
                'CreatedDate' => 'TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
                'UpdatedDate' => 'TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
            ],
            $tableOptions
        );

        $this->addPrimaryKey('PrimaryKey','{{%Language}}','LanguageCode');

        $insert=
            [
                ['aa', 'Afar'],
                ['ab', 'Abkhazian'],
                ['ae', 'Avestan'],
                ['af', 'Afrikaans'],
                ['ak', 'Akan'],
                ['am', 'Amharic'],
                ['an', 'Aragonese'],
                ['ar', 'Arabic'],
                ['as', 'Assamese'],
                ['av', 'Avaric'],
                ['ay', 'Aymara'],
                ['az', 'Azerbaijani'],
                ['ba', 'Bashkir'],
                ['be', 'Belarusian'],
                ['bg', 'Bulgarian'],
                ['bh', 'Bihari '],
                ['bi', 'Bislama'],
                ['bm', 'Bambara'],
                ['bn', 'Bengali'],
                ['bo', 'Tibetan'],
                ['br', 'Breton'],
                ['bs', 'Bosnian'],
                ['ca', 'Catalan'],
                ['ce', 'Chechen'],
                ['ch', 'Chamorro'],
                ['co', 'Corsican'],
                ['cr', 'Cree'],
                ['cs', 'Czech'],
                ['cu', 'Church Slavic'],
                ['cv', 'Chuvash'],
                ['cy', 'Welsh'],
                ['da', 'Danish'],
                ['de', 'German'],
                ['dv', 'Dhivehi'],
                ['dz', 'Dzongkha'],
                ['ee', 'Ewe'],
                ['el', 'Modern Greek (1453-)'],
                ['en', 'English'],
                ['eo', 'Esperanto'],
                ['es', 'Spanish'],
                ['et', 'Estonian'],
                ['eu', 'Basque'],
                ['fa', 'Persian'],
                ['ff', 'Fulah'],
                ['fi', 'Finnish'],
                ['fl','Pilipino'],
                ['fj', 'Fijian'],
                ['fo', 'Faroese'],
                ['fr', 'French'],
                ['fy', 'Western Frisian'],
                ['ga', 'Irish'],
                ['gd', 'Scottish Gaelic'],
                ['gl', 'Galician'],
                ['gn', 'Guarani'],
                ['gu', 'Gujarati'],
                ['gv', 'Manx'],
                ['ha', 'Hausa'],
                ['he', 'Hebrew'],
                ['hi', 'Hindi'],
                ['ho', 'Hiri Motu'],
                ['hr', 'Croatian'],
                ['ht', 'Haitian'],
                ['hu', 'Hungarian'],
                ['hy', 'Armenian'],
                ['hz', 'Herero'],
                ['ia', 'Interlingua (International Auxiliary Language Association)'],
                ['id', 'Indonesian'],
                ['ie', 'Interlingue'],
                ['ig', 'Igbo'],
                ['ii', 'Sichuan Yi'],
                ['ik', 'Inupiaq'],
                ['io', 'Ido'],
                ['is', 'Icelandic'],
                ['it', 'Italian'],
                ['iu', 'Inuktitut'],
                ['ja', 'Japanese'],
                ['jv', 'Javanese'],
                ['ka', 'Georgian'],
                ['kg', 'Kongo'],
                ['ki', 'Kikuyu'],
                ['kj', 'Kuanyama'],
                ['kk', 'Kazakh'],
                ['kl', 'Kalaallisut'],
                ['km', 'Central Khmer'],
                ['kn', 'Kannada'],
                ['ko', 'Korean'],
                ['kr', 'Kanuri'],
                ['ks', 'Kashmiri'],
                ['ku', 'Kurdish'],
                ['kv', 'Komi'],
                ['kw', 'Cornish'],
                ['ky', 'Kirghiz'],
                ['la', 'Latin'],
                ['lb', 'Luxembourgish'],
                ['lg', 'Ganda'],
                ['li', 'Limburgan'],
                ['ln', 'Lingala'],
                ['lo', 'Lao'],
                ['lt', 'Lithuanian'],
                ['lu', 'Luba-Katanga'],
                ['lv', 'Latvian'],
                ['mg', 'Malagasy'],
                ['mh', 'Marshallese'],
                ['mi', 'Maori'],
                ['mk', 'Macedonian'],
                ['ml', 'Malayalam'],
                ['mn', 'Mongolian'],
                ['mr', 'Marathi'],
                ['ms', 'Malay (macrolanguage)'],
                ['mt', 'Maltese'],
                ['my', 'Burmese'],
                ['na', 'Nauru'],
                ['nb', 'Norwegian Bokmål'],
                ['nd', 'North Ndebele'],
                ['ne', 'Nepali (macrolanguage)'],
                ['ng', 'Ndonga'],
                ['nl', 'Dutch'],
                ['nn', 'Norwegian Nynorsk'],
                ['no', 'Norwegian'],
                ['nr', 'South Ndebele'],
                ['nv', 'Navajo'],
                ['ny', 'Nyanja'],
                ['oc', 'Occitan (post 1500)'],
                ['oj', 'Ojibwa'],
                ['om', 'Oromo'],
                ['or', 'Oriya (macrolanguage)'],
                ['os', 'Ossetian'],
                ['pa', 'Panjabi'],
                ['pi', 'Pali'],
                ['pl', 'Polish'],
                ['ps', 'Pushto'],
                ['pt', 'Portuguese'],
                ['qu', 'Quechua'],
                ['rm', 'Romansh'],
                ['rn', 'Rundi'],
                ['ro', 'Romanian'],
                ['ru', 'Russian'],
                ['rw', 'Kinyarwanda'],
                ['sa', 'Sanskrit'],
                ['sc', 'Sardinian'],
                ['sd', 'Sindhi'],
                ['se', 'Northern Sami'],
                ['sg', 'Sango'],
                ['sh', 'Serbo-Croatian'],
                ['si', 'Sinhala'],
                ['sk', 'Slovak'],
                ['sl', 'Slovenian'],
                ['sm', 'Samoan'],
                ['sn', 'Shona'],
                ['so', 'Somali'],
                ['sq', 'Albanian'],
                ['sr', 'Serbian'],
                ['ss', 'Swati'],
                ['st', 'Southern Sotho'],
                ['su', 'Sundanese'],
                ['sv', 'Swedish'],
                ['sw', 'Swahili (macrolanguage)'],
                ['ta', 'Tamil'],
                ['te', 'Telugu'],
                ['tg', 'Tajik'],
                ['th', 'Thai'],
                ['ti', 'Tigrinya'],
                ['tk', 'Turkmen'],
                ['tl', 'Tagalog'],
                ['tn', 'Tswana'],
                ['to', 'Tonga (Tonga Islands)'],
                ['tr', 'Turkish'],
                ['ts', 'Tsonga'],
                ['tt', 'Tatar'],
                ['tw', 'Twi'],
                ['ty', 'Tahitian'],
                ['ug', 'Uighur'],
                ['uk', 'Ukrainian'],
                ['ur', 'Urdu'],
                ['uz', 'Uzbek'],
                ['ve', 'Venda'],
                ['vi', 'Vietnamese'],
                ['vo', 'Volapük'],
                ['wa', 'Walloon'],
                ['wo', 'Wolof'],
                ['xh', 'Xhosa'],
                ['yi', 'Yiddish'],
                ['yo', 'Yoruba'],
                ['za', 'Zhuang'],
                ['zh', 'Chinese'],
                ['zu', 'Zulu']
            ];

        $this->batchInsert('{{%Language}}',['LanguageCode','Name'],$insert);

        $this->update('{{%Language}}',['Status'=>'active'],['LanguageCode'=>'ru']);

        $this->createIndex('idx-Status-Sort','{{%Language}}',['Status','Sort']);



        $this->createTable('{{%LanguageTranslation}}', [
            'LanguageCode'=>"ENUM('aa','ab','ae','af','ak','am','an','ar','as','av','ay','az','ba','be','bg','bh',
                                        'bi','bm','bn','bo','br','bs','ca','ce','ch','co','cr','cs','cu','cv','cy','da',
                                        'de','dv','dz','ee','el','en','eo','es','et','eu','fa','ff','fi','fl','fj','fo','fr',
                                        'fy','ga','gd','gl','gn','gu','gv','ha','he','hi','ho','hr','ht','hu','hy','hz',
                                        'ia','id','ie','ig','ii','ik','io','is','it','iu','ja','jv','ka','kg','ki','kj',
                                        'kk','kl','km','kn','ko','kr','ks','ku','kv','kw','ky','la','lb','lg','li','ln',
                                        'lo','lt','lu','lv','mg','mh','mi','mk','ml','mn','mr','ms','mt','my','na','nb',
                                        'nd','ne','ng','nl','nn','no','nr','nv','ny','oc','oj','om','or','os','pa','pi',
                                        'pl','ps','pt','qu','rm','rn','ro','ru','rw','sa','sc','sd','se','sg','sh','si',
                                        'sk','sl','sm','sn','so','sq','sr','ss','st','su','sv','sw','ta','te','tg','th',
                                        'ti','tk','tl','tn','to','tr','ts','tt','tw','ty','ug','uk','ur','uz','ve','vi',
                                        'vo','wa','wo','xh','yi','yo','za','zh','zu')  NOT NULL ",

            'Language'=>$this->string(2)->notNull()->defaultValue('en')

            /*"ENUM('aa','ab','ae','af','ak','am','an','ar','as','av','ay','az','ba','be','bg','bh',
                                    'bi','bm','bn','bo','br','bs','ca','ce','ch','co','cr','cs','cu','cv','cy','da',
                                    'de','dv','dz','ee','el','en','eo','es','et','eu','fa','ff','fi','fl','fj','fo','fr',
                                    'fy','ga','gd','gl','gn','gu','gv','ha','he','hi','ho','hr','ht','hu','hy','hz',
                                    'ia','id','ie','ig','ii','ik','io','is','it','iu','ja','jv','ka','kg','ki','kj',
                                    'kk','kl','km','kn','ko','kr','ks','ku','kv','kw','ky','la','lb','lg','li','ln',
                                    'lo','lt','lu','lv','mg','mh','mi','mk','ml','mn','mr','ms','mt','my','na','nb',
                                    'nd','ne','ng','nl','nn','no','nr','nv','ny','oc','oj','om','or','os','pa','pi',
                                    'pl','ps','pt','qu','rm','rn','ro','ru','rw','sa','sc','sd','se','sg','sh','si',
                                    'sk','sl','sm','sn','so','sq','sr','ss','st','su','sv','sw','ta','te','tg','th',
                                    'ti','tk','tl','tn','to','tr','ts','tt','tw','ty','ug','uk','ur','uz','ve','vi',
                                    'vo','wa','wo','xh','yi','yo','za','zh','zu')  NOT NULL DEFAULT 'en'"*/,
            'Name' => $this->string(120)->notNull(),
            'CreatedDate' => 'TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'UpdatedDate' => 'TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
        ],
            $tableOptions." PARTITION BY LIST COLUMNS (`Language`)
(
					PARTITION r0 VALUES IN ('ru'),
                    PARTITION r1 VALUES IN ('be'),
                    PARTITION r2 VALUES IN ('aa'),
                    PARTITION r3 VALUES IN ('en')
)");
        /*
         *
         *   PARTITION BY KEY ((`Language`+0))
            PARTITIONS 186");

         *  PARTITION BY LIST(region_code) (
                    PARTITION r0 VALUES IN (1, 3),
                    PARTITION r1 VALUES IN (2, 5, 8),
                    PARTITION r2 VALUES IN (4, 9),
                    PARTITION r3 VALUES IN (6, 7, 10));

        */

        $this->addPrimaryKey('PrimaryKey','{{%LanguageTranslation}}',['LanguageCode','Language']);


        $insert=
            [
                ['aa', 'Afar'],
                ['ab', 'Abkhazian'],
                ['ae', 'Avestan'],
                ['af', 'Afrikaans'],
                ['ak', 'Akan'],
                ['am', 'Amharic'],
                ['an', 'Aragonese'],
                ['ar', 'Arabic'],
                ['as', 'Assamese'],
                ['av', 'Avaric'],
                ['ay', 'Aymara'],
                ['az', 'Azerbaijani'],
                ['ba', 'Bashkir'],
                ['be', 'Belarusian'],
                ['bg', 'Bulgarian'],
                ['bh', 'Bihari '],
                ['bi', 'Bislama'],
                ['bm', 'Bambara'],
                ['bn', 'Bengali'],
                ['bo', 'Tibetan'],
                ['br', 'Breton'],
                ['bs', 'Bosnian'],
                ['ca', 'Catalan'],
                ['ce', 'Chechen'],
                ['ch', 'Chamorro'],
                ['co', 'Corsican'],
                ['cr', 'Cree'],
                ['cs', 'Czech'],
                ['cu', 'Church Slavic'],
                ['cv', 'Chuvash'],
                ['cy', 'Welsh'],
                ['da', 'Danish'],
                ['de', 'German'],
                ['dv', 'Dhivehi'],
                ['dz', 'Dzongkha'],
                ['ee', 'Ewe'],
                ['el', 'Greek'],
                ['en', 'English'],
                ['eo', 'Esperanto'],
                ['es', 'Spanish'],
                ['et', 'Estonian'],
                ['eu', 'Basque'],
                ['fa', 'Persian'],
                ['ff', 'Fulah'],
                ['fi', 'Finnish'],
                ['fl','Pilipino'],
                ['fj', 'Fijian'],
                ['fo', 'Faroese'],
                ['fr', 'French'],
                ['fy', 'Western Frisian'],
                ['ga', 'Irish'],
                ['gd', 'Scottish Gaelic'],
                ['gl', 'Galician'],
                ['gn', 'Guarani'],
                ['gu', 'Gujarati'],
                ['gv', 'Manx'],
                ['ha', 'Hausa'],
                ['he', 'Hebrew'],
                ['hi', 'Hindi'],
                ['ho', 'Hiri Motu'],
                ['hr', 'Croatian'],
                ['ht', 'Haitian'],
                ['hu', 'Hungarian'],
                ['hy', 'Armenian'],
                ['hz', 'Herero'],
                ['ia', 'Interlingua'],
                ['id', 'Indonesian'],
                ['ie', 'Interlingue'],
                ['ig', 'Igbo'],
                ['ii', 'Sichuan Yi'],
                ['ik', 'Inupiaq'],
                ['io', 'Ido'],
                ['is', 'Icelandic'],
                ['it', 'Italian'],
                ['iu', 'Inuktitut'],
                ['ja', 'Japanese'],
                ['jv', 'Javanese'],
                ['ka', 'Georgian'],
                ['kg', 'Kongo'],
                ['ki', 'Kikuyu'],
                ['kj', 'Kuanyama'],
                ['kk', 'Kazakh'],
                ['kl', 'Kalaallisut'],
                ['km', 'Central Khmer'],
                ['kn', 'Kannada'],
                ['ko', 'Korean'],
                ['kr', 'Kanuri'],
                ['ks', 'Kashmiri'],
                ['ku', 'Kurdish'],
                ['kv', 'Komi'],
                ['kw', 'Cornish'],
                ['ky', 'Kirghiz'],
                ['la', 'Latin'],
                ['lb', 'Luxembourgish'],
                ['lg', 'Ganda'],
                ['li', 'Limburgan'],
                ['ln', 'Lingala'],
                ['lo', 'Lao'],
                ['lt', 'Lithuanian'],
                ['lu', 'Luba-Katanga'],
                ['lv', 'Latvian'],
                ['mg', 'Malagasy'],
                ['mh', 'Marshallese'],
                ['mi', 'Maori'],
                ['mk', 'Macedonian'],
                ['ml', 'Malayalam'],
                ['mn', 'Mongolian'],
                ['mr', 'Marathi'],
                ['ms', 'Malay'],
                ['mt', 'Maltese'],
                ['my', 'Burmese'],
                ['na', 'Nauru'],
                ['nb', 'Norwegian Bokmål'],
                ['nd', 'North Ndebele'],
                ['ne', 'Nepali'],
                ['ng', 'Ndonga'],
                ['nl', 'Dutch'],
                ['nn', 'Norwegian Nynorsk'],
                ['no', 'Norwegian'],
                ['nr', 'South Ndebele'],
                ['nv', 'Navajo'],
                ['ny', 'Nyanja'],
                ['oc', 'Occitan'],
                ['oj', 'Ojibwa'],
                ['om', 'Oromo'],
                ['or', 'Oriya'],
                ['os', 'Ossetian'],
                ['pa', 'Panjabi'],
                ['pi', 'Pali'],
                ['pl', 'Polish'],
                ['ps', 'Pushto'],
                ['pt', 'Portuguese'],
                ['qu', 'Quechua'],
                ['rm', 'Romansh'],
                ['rn', 'Rundi'],
                ['ro', 'Romanian'],
                ['ru', 'Russian'],
                ['rw', 'Kinyarwanda'],
                ['sa', 'Sanskrit'],
                ['sc', 'Sardinian'],
                ['sd', 'Sindhi'],
                ['se', 'Northern Sami'],
                ['sg', 'Sango'],
                ['sh', 'Serbo-Croatian'],
                ['si', 'Sinhala'],
                ['sk', 'Slovak'],
                ['sl', 'Slovenian'],
                ['sm', 'Samoan'],
                ['sn', 'Shona'],
                ['so', 'Somali'],
                ['sq', 'Albanian'],
                ['sr', 'Serbian'],
                ['ss', 'Swati'],
                ['st', 'Southern Sotho'],
                ['su', 'Sundanese'],
                ['sv', 'Swedish'],
                ['sw', 'Swahili'],
                ['ta', 'Tamil'],
                ['te', 'Telugu'],
                ['tg', 'Tajik'],
                ['th', 'Thai'],
                ['ti', 'Tigrinya'],
                ['tk', 'Turkmen'],
                ['tl', 'Tagalog'],
                ['tn', 'Tswana'],
                ['to', 'Tonga'],
                ['tr', 'Turkish'],
                ['ts', 'Tsonga'],
                ['tt', 'Tatar'],
                ['tw', 'Twi'],
                ['ty', 'Tahitian'],
                ['ug', 'Uighur'],
                ['uk', 'Ukrainian'],
                ['ur', 'Urdu'],
                ['uz', 'Uzbek'],
                ['ve', 'Venda'],
                ['vi', 'Vietnamese'],
                ['vo', 'Volapük'],
                ['wa', 'Walloon'],
                ['wo', 'Wolof'],
                ['xh', 'Xhosa'],
                ['yi', 'Yiddish'],
                ['yo', 'Yoruba'],
                ['za', 'Zhuang'],
                ['zh', 'Chinese'],
                ['zu', 'Zulu']
            ];

        $this->batchInsert('{{%LanguageTranslation}}',['LanguageCode','Name'],$insert);

        $insert=[
            ['Абхазский', 'ab','ru'],
            ['Аварский', 'av','ru'],
            ['Авестийский', 'ae','ru'],
            ['Азербайджанский', 'az','ru'],
            ['Аймара', 'ay','ru'],
            ['Акан', 'ak','ru'],
            ['Албанский', 'sq','ru'],
            ['Амхарский', 'am','ru'],
            ['Английский', 'en','ru'],
            ['Арабский', 'ar','ru'],
            ['Армянский', 'hy','ru'],
            ['Ассамский', 'as','ru'],
            ['Афарский', 'aa','ru'],
            ['Африкаанс', 'af','ru'],
            ['Бамбара', 'bm','ru'],
            ['Баскский', 'eu','ru'],
            ['Башкирский', 'ba','ru'],
            ['Белорусский', 'be','ru'],
            ['Бенгальский', 'bn','ru'],
            ['Бирманский', 'my','ru'],
            ['Бислама', 'bi','ru'],
            ['Болгарский', 'bg','ru'],
            ['Боснийский', 'bs','ru'],
            ['Бретонский', 'br','ru'],
            ['Валлийский', 'cy','ru'],
            ['Венгерский', 'hu','ru'],
            ['Венда', 've','ru'],
            ['Волапюк', 'vo','ru'],
            ['Волоф', 'wo','ru'],
            ['Вьетнамский', 'vi','ru'],
            ['Галисийский', 'gl','ru'],
            ['Ганда', 'lg','ru'],
            ['Гереро', 'hz','ru'],
            ['Гренландский', 'kl','ru'],
            ['Греческий', 'el','ru'],
            ['Грузинский', 'ka','ru'],
            ['Гуарани', 'gn','ru'],
            ['Гуджарати', 'gu','ru'],
            ['Гэльский', 'gd','ru'],
            ['Датский', 'da','ru'],
            ['Дзонг-кэ', 'dz','ru'],
            ['Дивехи', 'dv','ru'],
            ['Зулу', 'zu','ru'],
            ['Иврит', 'he','ru'],
            ['Игбо', 'ig','ru'],
            ['Идиш', 'yi','ru'],
            ['Индонезийский', 'id','ru'],
            ['Интерлингва', 'ia','ru'],
            ['Интерлингве', 'ie','ru'],
            ['Инуктитут', 'iu','ru'],
            ['Инупиак', 'ik','ru'],
            ['Ирландский', 'ga','ru'],
            ['Исландский', 'is','ru'],
            ['Испанский', 'es','ru'],
            ['Итальянский', 'it','ru'],
            ['Йоруба', 'yo','ru'],
            ['Казахский', 'kk','ru'],
            ['Каннада', 'kn','ru'],
            ['Канури', 'kr','ru'],
            ['Каталанский', 'ca','ru'],
            ['Кашмири', 'ks','ru'],
            ['Кечуа', 'qu','ru'],
            ['Кикуйю', 'ki','ru'],
            ['Киньяма', 'kj','ru'],
            ['Киргизский', 'ky','ru'],
            ['Китайский', 'zh','ru'],
            ['Коми', 'kv','ru'],
            ['Конго', 'kg','ru'],
            ['Корейский', 'ko','ru'],
            ['Корнский', 'kw','ru'],
            ['Корсиканский', 'co','ru'],
            ['Коса', 'xh','ru'],
            ['Курдский', 'ku','ru'],
            ['Кхмерский', 'km','ru'],
            ['Лаосский', 'lo','ru'],
            ['Латинский', 'la','ru'],
            ['Латышский', 'lv','ru'],
            ['Лингала', 'ln','ru'],
            ['Литовский', 'lt','ru'],
            ['Луба-катанга', 'lu','ru'],
            ['Люксембургский', 'lb','ru'],
            ['Македонский', 'mk','ru'],
            ['Малагасийский', 'mg','ru'],
            ['Малайский', 'ms','ru'],
            ['Малаялам', 'ml','ru'],
            ['Мальтийский', 'mt','ru'],
            ['Маори', 'mi','ru'],
            ['Маратхи', 'mr','ru'],
            ['Маршалльский', 'mh','ru'],
            // ['Мерянский', 'me','ru'],
            ['Монгольский', 'mn','ru'],
            ['Мэнский', 'gv','ru'],
            ['Навахо', 'nv','ru'],
            ['Науру', 'na','ru'],
            ['Ндебеле северный', 'nd','ru'],
            ['Ндебеле южный', 'nr','ru'],
            ['Ндунга', 'ng','ru'],
            ['Немецкий', 'de','ru'],
            ['Непальский', 'ne','ru'],
            ['Нидерландский', 'nl','ru'],
            ['Норвежский', 'no','ru'],
            ['Ньянджа', 'ny','ru'],
            ['Новонорвежский', 'nn','ru'],
            ['Оджибве', 'oj','ru'],
            ['Окситанский', 'oc','ru'],
            ['Ория', 'or','ru'],
            ['Оромо', 'om','ru'],
            ['Осетинский', 'os','ru'],
            ['Пали', 'pi','ru'],
            ['Пенджабский', 'pa','ru'],
            ['Персидский', 'fa','ru'],
            ['Польский', 'pl','ru'],
            ['Португальский', 'pt','ru'],
            ['Пушту', 'ps','ru'],
            ['Ретороманский', 'rm','ru'],
            ['Руанда', 'rw','ru'],
            ['Румынский', 'ro','ru'],
            ['Рунди', 'rn','ru'],
            ['Русский', 'ru','ru'],
            ['Самоанский', 'sm','ru'],
            ['Санго', 'sg','ru'],
            ['Санскрит', 'sa','ru'],
            ['Сардинский', 'sc','ru'],
            ['Свази', 'ss','ru'],
            ['Сербский', 'sr','ru'],
            ['Сингальский', 'si','ru'],
            ['Синдхи', 'sd','ru'],
            ['Словацкий', 'sk','ru'],
            ['Словенский', 'sl','ru'],
            ['Сомали', 'so','ru'],
            ['Сото южный', 'st','ru'],
            ['Суахили', 'sw','ru'],
            ['Сунданский', 'su','ru'],
            ['Тагальский', 'tl','ru'],
            ['Таджикский', 'tg','ru'],
            ['Тайский', 'th','ru'],
            ['Таитянский', 'ty','ru'],
            ['Тамильский', 'ta','ru'],
            ['Татарский', 'tt','ru'],
            ['Тви', 'tw','ru'],
            ['Телугу', 'te','ru'],
            ['Тибетский', 'bo','ru'],
            ['Тигринья', 'ti','ru'],
            ['Тонганский', 'to','ru'],
            ['Тсвана', 'tn','ru'],
            ['Тсонга', 'ts','ru'],
            ['Турецкий', 'tr','ru'],
            ['Туркменский', 'tk','ru'],
            ['Узбекский', 'uz','ru'],
            ['Уйгурский', 'ug','ru'],
            ['Украинский', 'uk','ru'],
            ['Урду', 'ur','ru'],
            ['Фарерский', 'fo','ru'],
            ['Фиджи', 'fj','ru'],
            ['Филиппинский', 'fl','ru'],
            ['Финский', 'fi','ru'],
            ['Французский', 'fr','ru'],
            ['Фризский', 'fy','ru'],
            ['Фулах', 'ff','ru'],
            ['Хауса', 'ha','ru'],
            ['Хинди', 'hi','ru'],
            ['Хиримоту', 'ho','ru'],
            ['Хорватский', 'hr','ru'],
            ['Старославянский', 'cu','ru'],
            ['Чаморро', 'ch','ru'],
            ['Чеченский', 'ce','ru'],
            ['Чешский', 'cs','ru'],
            ['Чжуанский', 'za','ru'],
            ['Чувашский', 'cv','ru'],
            ['Шведский', 'sv','ru'],
            ['Шона', 'sn','ru'],
            ['Эве', 'ee','ru'],
            ['Эсперанто', 'eo','ru'],
            ['Эстонский', 'et','ru'],
            ['Яванский', 'jv','ru'],
            ['Японский', 'ja','ru']
        ];

        $this->batchInsert('{{%LanguageTranslation}}',['Name','LanguageCode','Language'],$insert);
        $insert=[
            ['Абхазский', 'ab','be'],
            ['Аварский', 'av','be'],
            ['Авестийский', 'ae','be'],
            ['Азербайджанский', 'az','be'],
            ['Аймара', 'ay','be'],
            ['Акан', 'ak','be'],
            ['Албанский', 'sq','be'],
            ['Амхарский', 'am','be'],
            ['Английский', 'en','be'],
            ['Арабский', 'ar','be'],
            ['Армянский', 'hy','be'],
            ['Ассамский', 'as','be'],
            ['Афарский', 'aa','be'],
            ['Африкаанс', 'af','be'],
            ['Бамбара', 'bm','be'],
            ['Баскский', 'eu','be'],
            ['Башкирский', 'ba','be'],
            ['Белорусский', 'be','be'],
            ['Бенгальский', 'bn','be'],
            ['Бирманский', 'my','be'],
            ['Бислама', 'bi','be'],
            ['Болгарский', 'bg','be'],
            ['Боснийский', 'bs','be'],
            ['Бретонский', 'br','be'],
            ['Валлийский', 'cy','be'],
            ['Венгерский', 'hu','be'],
            ['Венда', 've','be'],
            ['Волапюк', 'vo','be'],
            ['Волоф', 'wo','be'],
            ['Вьетнамский', 'vi','be'],
            ['Галисийский', 'gl','be'],
            ['Ганда', 'lg','be'],
            ['Гереро', 'hz','be'],
            ['Гренландский', 'kl','be'],
            ['Греческий', 'el','be'],
            ['Грузинский', 'ka','be'],
            ['Гуарани', 'gn','be'],
            ['Гуджарати', 'gu','be'],
            ['Гэльский', 'gd','be'],
            ['Датский', 'da','be'],
            ['Дзонг-кэ', 'dz','be'],
            ['Дивехи', 'dv','be'],
            ['Зулу', 'zu','be'],
            ['Иврит', 'he','be'],
            ['Игбо', 'ig','be'],
            ['Идиш', 'yi','be'],
            ['Индонезийский', 'id','be'],
            ['Интерлингва', 'ia','be'],
            ['Интерлингве', 'ie','be'],
            ['Инуктитут', 'iu','be'],
            ['Инупиак', 'ik','be'],
            ['Ирландский', 'ga','be'],
            ['Исландский', 'is','be'],
            ['Испанский', 'es','be'],
            ['Итальянский', 'it','be'],
            ['Йоруба', 'yo','be'],
            ['Казахский', 'kk','be'],
            ['Каннада', 'kn','be'],
            ['Канури', 'kr','be'],
            ['Каталанский', 'ca','be'],
            ['Кашмири', 'ks','be'],
            ['Кечуа', 'qu','be'],
            ['Кикуйю', 'ki','be'],
            ['Киньяма', 'kj','be'],
            ['Киргизский', 'ky','be'],
            ['Китайский', 'zh','be'],
            ['Коми', 'kv','be'],
            ['Конго', 'kg','be'],
            ['Корейский', 'ko','be'],
            ['Корнский', 'kw','be'],
            ['Корсиканский', 'co','be'],
            ['Коса', 'xh','be'],
            ['Курдский', 'ku','be'],
            ['Кхмерский', 'km','be'],
            ['Лаосский', 'lo','be'],
            ['Латинский', 'la','be'],
            ['Латышский', 'lv','be'],
            ['Лингала', 'ln','be'],
            ['Литовский', 'lt','be'],
            ['Луба-катанга', 'lu','be'],
            ['Люксембургский', 'lb','be'],
            ['Македонский', 'mk','be'],
            ['Малагасийский', 'mg','be'],
            ['Малайский', 'ms','be'],
            ['Малаялам', 'ml','be'],
            ['Мальтийский', 'mt','be'],
            ['Маори', 'mi','be'],
            ['Маратхи', 'mr','be'],
            ['Маршалльский', 'mh','be'],
            // ['Мерянский', 'me','be'],
            ['Монгольский', 'mn','be'],
            ['Мэнский', 'gv','be'],
            ['Навахо', 'nv','be'],
            ['Науру', 'na','be'],
            ['Ндебеле северный', 'nd','be'],
            ['Ндебеле южный', 'nr','be'],
            ['Ндунга', 'ng','be'],
            ['Немецкий', 'de','be'],
            ['Непальский', 'ne','be'],
            ['Нидерландский', 'nl','be'],
            ['Норвежский', 'no','be'],
            ['Ньянджа', 'ny','be'],
            ['Новонорвежский', 'nn','be'],
            ['Оджибве', 'oj','be'],
            ['Окситанский', 'oc','be'],
            ['Ория', 'or','be'],
            ['Оромо', 'om','be'],
            ['Осетинский', 'os','be'],
            ['Пали', 'pi','be'],
            ['Пенджабский', 'pa','be'],
            ['Персидский', 'fa','be'],
            ['Польский', 'pl','be'],
            ['Португальский', 'pt','be'],
            ['Пушту', 'ps','be'],
            ['Ретороманский', 'rm','be'],
            ['Руанда', 'rw','be'],
            ['Румынский', 'ro','be'],
            ['Рунди', 'rn','be'],
            ['Русский', 'ru','be'],
            ['Самоанский', 'sm','be'],
            ['Санго', 'sg','be'],
            ['Санскрит', 'sa','be'],
            ['Сардинский', 'sc','be'],
            ['Свази', 'ss','be'],
            ['Сербский', 'sr','be'],
            ['Сингальский', 'si','be'],
            ['Синдхи', 'sd','be'],
            ['Словацкий', 'sk','be'],
            ['Словенский', 'sl','be'],
            ['Сомали', 'so','be'],
            ['Сото южный', 'st','be'],
            ['Суахили', 'sw','be'],
            ['Сунданский', 'su','be'],
            ['Тагальский', 'tl','be'],
            ['Таджикский', 'tg','be'],
            ['Тайский', 'th','be'],
            ['Таитянский', 'ty','be'],
            ['Тамильский', 'ta','be'],
            ['Татарский', 'tt','be'],
            ['Тви', 'tw','be'],
            ['Телугу', 'te','be'],
            ['Тибетский', 'bo','be'],
            ['Тигринья', 'ti','be'],
            ['Тонганский', 'to','be'],
            ['Тсвана', 'tn','be'],
            ['Тсонга', 'ts','be'],
            ['Турецкий', 'tr','be'],
            ['Туркменский', 'tk','be'],
            ['Узбекский', 'uz','be'],
            ['Уйгурский', 'ug','be'],
            ['Украинский', 'uk','be'],
            ['Урду', 'ur','be'],
            ['Фарерский', 'fo','be'],
            ['Фиджи', 'fj','be'],
            ['Филиппинский', 'fl','be'],
            ['Финский', 'fi','be'],
            ['Французский', 'fr','be'],
            ['Фризский', 'fy','be'],
            ['Фулах', 'ff','be'],
            ['Хауса', 'ha','be'],
            ['Хинди', 'hi','be'],
            ['Хиримоту', 'ho','be'],
            ['Хорватский', 'hr','be'],
            ['Старославянский', 'cu','be'],
            ['Чаморро', 'ch','be'],
            ['Чеченский', 'ce','be'],
            ['Чешский', 'cs','be'],
            ['Чжуанский', 'za','be'],
            ['Чувашский', 'cv','be'],
            ['Шведский', 'sv','be'],
            ['Шона', 'sn','be'],
            ['Эве', 'ee','be'],
            ['Эсперанто', 'eo','be'],
            ['Эстонский', 'et','be'],
            ['Яванский', 'jv','be'],
            ['Японский', 'ja','be']
        ];
        $this->batchInsert('{{%LanguageTranslation}}',['Name','LanguageCode','Language'],$insert);


        $insert=[
            ['Абхазский', 'ab','aa'],
            ['Аварский', 'av','aa'],
            ['Авестийский', 'ae','aa'],
            ['Азербайджанский', 'az','aa'],
            ['Аймара', 'ay','aa'],
            ['Акан', 'ak','aa'],
            ['Албанский', 'sq','aa'],
            ['Амхарский', 'am','aa'],
            ['Английский', 'en','aa'],
            ['Арабский', 'ar','aa'],
            ['Армянский', 'hy','aa'],
            ['Ассамский', 'as','aa'],
            ['Афарский', 'aa','aa'],
            ['Африкаанс', 'af','aa'],
            ['Бамбара', 'bm','aa'],
            ['Баскский', 'eu','aa'],
            ['Башкирский', 'ba','aa'],
            ['Белорусский', 'be','aa'],
            ['Бенгальский', 'bn','aa'],
            ['Бирманский', 'my','aa'],
            ['Бислама', 'bi','aa'],
            ['Болгарский', 'bg','aa'],
            ['Боснийский', 'bs','aa'],
            ['Бретонский', 'br','aa'],
            ['Валлийский', 'cy','aa'],
            ['Венгерский', 'hu','aa'],
            ['Венда', 've','aa'],
            ['Волапюк', 'vo','aa'],
            ['Волоф', 'wo','aa'],
            ['Вьетнамский', 'vi','aa'],
            ['Галисийский', 'gl','aa'],
            ['Ганда', 'lg','aa'],
            ['Гереро', 'hz','aa'],
            ['Гренландский', 'kl','aa'],
            ['Греческий', 'el','aa'],
            ['Грузинский', 'ka','aa'],
            ['Гуарани', 'gn','aa'],
            ['Гуджарати', 'gu','aa'],
            ['Гэльский', 'gd','aa'],
            ['Датский', 'da','aa'],
            ['Дзонг-кэ', 'dz','aa'],
            ['Дивехи', 'dv','aa'],
            ['Зулу', 'zu','aa'],
            ['Иврит', 'he','aa'],
            ['Игбо', 'ig','aa'],
            ['Идиш', 'yi','aa'],
            ['Индонезийский', 'id','aa'],
            ['Интерлингва', 'ia','aa'],
            ['Интерлингве', 'ie','aa'],
            ['Инуктитут', 'iu','aa'],
            ['Инупиак', 'ik','aa'],
            ['Ирландский', 'ga','aa'],
            ['Исландский', 'is','aa'],
            ['Испанский', 'es','aa'],
            ['Итальянский', 'it','aa'],
            ['Йоруба', 'yo','aa'],
            ['Казахский', 'kk','aa'],
            ['Каннада', 'kn','aa'],
            ['Канури', 'kr','aa'],
            ['Каталанский', 'ca','aa'],
            ['Кашмири', 'ks','aa'],
            ['Кечуа', 'qu','aa'],
            ['Кикуйю', 'ki','aa'],
            ['Киньяма', 'kj','aa'],
            ['Киргизский', 'ky','aa'],
            ['Китайский', 'zh','aa'],
            ['Коми', 'kv','aa'],
            ['Конго', 'kg','aa'],
            ['Корейский', 'ko','aa'],
            ['Корнский', 'kw','aa'],
            ['Корсиканский', 'co','aa'],
            ['Коса', 'xh','aa'],
            ['Курдский', 'ku','aa'],
            ['Кхмерский', 'km','aa'],
            ['Лаосский', 'lo','aa'],
            ['Латинский', 'la','aa'],
            ['Латышский', 'lv','aa'],
            ['Лингала', 'ln','aa'],
            ['Литовский', 'lt','aa'],
            ['Луба-катанга', 'lu','aa'],
            ['Люксембургский', 'lb','aa'],
            ['Македонский', 'mk','aa'],
            ['Малагасийский', 'mg','aa'],
            ['Малайский', 'ms','aa'],
            ['Малаялам', 'ml','aa'],
            ['Мальтийский', 'mt','aa'],
            ['Маори', 'mi','aa'],
            ['Маратхи', 'mr','aa'],
            ['Маршалльский', 'mh','aa'],
            // ['Мерянский', 'me','aa'],
            ['Монгольский', 'mn','aa'],
            ['Мэнский', 'gv','aa'],
            ['Навахо', 'nv','aa'],
            ['Науру', 'na','aa'],
            ['Ндебеле северный', 'nd','aa'],
            ['Ндебеле южный', 'nr','aa'],
            ['Ндунга', 'ng','aa'],
            ['Немецкий', 'de','aa'],
            ['Непальский', 'ne','aa'],
            ['Нидерландский', 'nl','aa'],
            ['Норвежский', 'no','aa'],
            ['Ньянджа', 'ny','aa'],
            ['Новонорвежский', 'nn','aa'],
            ['Оджибве', 'oj','aa'],
            ['Окситанский', 'oc','aa'],
            ['Ория', 'or','aa'],
            ['Оромо', 'om','aa'],
            ['Осетинский', 'os','aa'],
            ['Пали', 'pi','aa'],
            ['Пенджабский', 'pa','aa'],
            ['Персидский', 'fa','aa'],
            ['Польский', 'pl','aa'],
            ['Португальский', 'pt','aa'],
            ['Пушту', 'ps','aa'],
            ['Ретороманский', 'rm','aa'],
            ['Руанда', 'rw','aa'],
            ['Румынский', 'ro','aa'],
            ['Рунди', 'rn','aa'],
            ['Русский', 'ru','aa'],
            ['Самоанский', 'sm','aa'],
            ['Санго', 'sg','aa'],
            ['Санскрит', 'sa','aa'],
            ['Сардинский', 'sc','aa'],
            ['Свази', 'ss','aa'],
            ['Сербский', 'sr','aa'],
            ['Сингальский', 'si','aa'],
            ['Синдхи', 'sd','aa'],
            ['Словацкий', 'sk','aa'],
            ['Словенский', 'sl','aa'],
            ['Сомали', 'so','aa'],
            ['Сото южный', 'st','aa'],
            ['Суахили', 'sw','aa'],
            ['Сунданский', 'su','aa'],
            ['Тагальский', 'tl','aa'],
            ['Таджикский', 'tg','aa'],
            ['Тайский', 'th','aa'],
            ['Таитянский', 'ty','aa'],
            ['Тамильский', 'ta','aa'],
            ['Татарский', 'tt','aa'],
            ['Тви', 'tw','aa'],
            ['Телугу', 'te','aa'],
            ['Тибетский', 'bo','aa'],
            ['Тигринья', 'ti','aa'],
            ['Тонганский', 'to','aa'],
            ['Тсвана', 'tn','aa'],
            ['Тсонга', 'ts','aa'],
            ['Турецкий', 'tr','aa'],
            ['Туркменский', 'tk','aa'],
            ['Узбекский', 'uz','aa'],
            ['Уйгурский', 'ug','aa'],
            ['Украинский', 'uk','aa'],
            ['Урду', 'ur','aa'],
            ['Фарерский', 'fo','aa'],
            ['Фиджи', 'fj','aa'],
            ['Филиппинский', 'fl','aa'],
            ['Финский', 'fi','aa'],
            ['Французский', 'fr','aa'],
            ['Фризский', 'fy','aa'],
            ['Фулах', 'ff','aa'],
            ['Хауса', 'ha','aa'],
            ['Хинди', 'hi','aa'],
            ['Хиримоту', 'ho','aa'],
            ['Хорватский', 'hr','aa'],
            ['Старославянский', 'cu','aa'],
            ['Чаморро', 'ch','aa'],
            ['Чеченский', 'ce','aa'],
            ['Чешский', 'cs','aa'],
            ['Чжуанский', 'za','aa'],
            ['Чувашский', 'cv','aa'],
            ['Шведский', 'sv','aa'],
            ['Шона', 'sn','aa'],
            ['Эве', 'ee','aa'],
            ['Эсперанто', 'eo','aa'],
            ['Эстонский', 'et','aa'],
            ['Яванский', 'jv','aa'],
            ['Японский', 'ja','aa']
        ];
        $this->batchInsert('{{%LanguageTranslation}}',['Name','LanguageCode','Language'],$insert);
        //  $this->addForeignKey('fk_LanguageTranslation_Language', '{{%LanguageTranslation}}', 'LanguageCode', '{{%Language}}', 'LanguageCode', 'CASCADE', 'RESTRICT');
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        //$this->dropForeignKey('fk_LanguageTranslation_Language', '{{%LanguageTranslation}}');
        $this->dropTable('{{%LanguageTranslation}}');
        $this->dropTable('{{%Language}}');
    }
}
